### ISSUE TITLE
Error: Serialization of 'Closure' is not allowed in FileStore.php:98

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#1065]
Can't seem to track down the cause of this production error. Any help would be appreciated. 👍 

**Settings**

```
settings:
  assets:
    image_manipulation_cached: false
  caching:
    stache_always_update: false
    static_caching_enabled: true
    static_caching_type: cache
```

**Statamic version:** 2.1.15

**List of installed addons:**
CacheManager
Lynx
Metapod
Spock
SVGoutput
TaxonomySlug
### Logs

```
[2016-10-25 04:30:34] production.ERROR: Exception: Serialization of 'Closure' is not allowed in /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:98
Stack trace:
#0 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(98): serialize(Object(Illuminate\Http\RedirectResponse))
#1 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('static_cache.b1...', Object(Illuminate\Http\RedirectResponse), 0)
#2 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(184): Illuminate\Cache\FileStore->forever('static_cache.b1...', Object(Illuminate\Http\RedirectResponse))
#3 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/AbstractCacher.php(72): Illuminate\Cache\Repository->forever('static_cache.b1...', Object(Illuminate\Http\RedirectResponse))
#4 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/ApplicationCacher.php(43): Statamic\StaticCaching\AbstractCacher->putInCache('static_cache.b1...', Object(Illuminate\Http\RedirectResponse), NULL)
#5 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/Middleware/Cache.php(46): Statamic\StaticCaching\ApplicationCacher->cachePage(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#6 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Statamic\StaticCaching\Middleware\Cache->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#7 /home/forge/www.trychameleon.com/index.php(132): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#8 {main}  
[2016-10-25 08:13:03] production.NOTICE: Error in [collapse] modifier: array_merge(): Argument #2 is not an array  
[2016-10-25 12:21:57] production.ERROR: Exception: Serialization of 'Closure' is not allowed in /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:98
Stack trace:
#0 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(98): serialize(Object(Illuminate\Http\RedirectResponse))
#1 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('static_cache.74...', Object(Illuminate\Http\RedirectResponse), 0)
#2 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(184): Illuminate\Cache\FileStore->forever('static_cache.74...', Object(Illuminate\Http\RedirectResponse))
#3 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/AbstractCacher.php(72): Illuminate\Cache\Repository->forever('static_cache.74...', Object(Illuminate\Http\RedirectResponse))
#4 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/ApplicationCacher.php(43): Statamic\StaticCaching\AbstractCacher->putInCache('static_cache.74...', Object(Illuminate\Http\RedirectResponse), NULL)
#5 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/Middleware/Cache.php(46): Statamic\StaticCaching\ApplicationCacher->cachePage(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#6 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Statamic\StaticCaching\Middleware\Cache->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#7 /home/forge/www.trychameleon.com/index.php(132): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#8 {main}  
[2016-10-25 15:06:04] production.ERROR: Exception: Serialization of 'Closure' is not allowed in /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:98
Stack trace:
#0 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(98): serialize(Object(Illuminate\Http\RedirectResponse))
#1 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('static_cache.b1...', Object(Illuminate\Http\RedirectResponse), 0)
#2 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(184): Illuminate\Cache\FileStore->forever('static_cache.b1...', Object(Illuminate\Http\RedirectResponse))
#3 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/AbstractCacher.php(72): Illuminate\Cache\Repository->forever('static_cache.b1...', Object(Illuminate\Http\RedirectResponse))
#4 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/ApplicationCacher.php(43): Statamic\StaticCaching\AbstractCacher->putInCache('static_cache.b1...', Object(Illuminate\Http\RedirectResponse), NULL)
#5 /home/forge/www.trychameleon.com/statamic/core/StaticCaching/Middleware/Cache.php(46): Statamic\StaticCaching\ApplicationCacher->cachePage(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#6 /home/forge/www.trychameleon.com/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Statamic\StaticCaching\Middleware\Cache->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#7 /home/forge/www.trychameleon.com/index.php(132): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#8 {main}  

```

**Comment by jackmcdade** [comment]
Are you still having this issue in 2.1.19?

**Comment by mikemartin** [comment]
I'll be completely honest, I don't remember how I triggered this error in the first place. Clearly I didn't include enough information to reproduce the error. I just upgraded to 2.1.19 and will let you know if it pops up again.

**Comment by jackmcdade** [comment]
Sounds good! Feel free to reopen if so.
