### ISSUE TITLE
Error when searching on production

### ISSUE THREAD

**Issue by brettdewoody** [statamic/v2-hub#1079]
I'm receiving an error when I perform a search on my production site. Search works fine on local. The main difference between the two environments is caching is enabled on production.  On production:

    APP_STATIC_CACHING=true
    APP_STATIC_CACHING_TYPE=cache

On local

    APP_STATIC_CACHING=false

The error is the typical 'Whoops, looks like something went wrong.' error page. 

### Server configuration
**Web server:**
Apache 

**PHP version:**
7.0.10

**Statamic version:**
2.1.17

### Logs
```
[16:29:49] LOG.error: ZendSearch\Lucene\Exception\RuntimeException in /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Storage/File/Filesystem.php:55
Stack trace:
#0 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Storage/Directory/Filesystem.php(172): ZendSearch\Lucene\Storage\File\Filesystem->__construct('/var/www/html/l...', 'w+b')
#1 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index/SegmentInfo.php(777): ZendSearch\Lucene\Storage\Directory\Filesystem->createFile('_51.sti')
#2 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index/SegmentInfo.php(803): ZendSearch\Lucene\Index\SegmentInfo->_loadDictionaryIndex()
#3 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php(898): ZendSearch\Lucene\Index\SegmentInfo->getTermInfo(Object(ZendSearch\Lucene\Index\Term))
#4 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Search/Query/Preprocessing/Term.php(120): ZendSearch\Lucene\Index->hasTerm(Object(ZendSearch\Lucene\Index\Term))
#5 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Search/Query/Preprocessing/Term.php(93): ZendSearch\Lucene\Search\Query\Preprocessing\Term->rewrite(Object(ZendSearch\Lucene\Index))
#6 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(132): ZendSearch\Lucene\Search\Query\Preprocessing\Term->rewrite(Object(ZendSearch\Lucene\Index))
#7 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Search/Query/Boolean.php(132): ZendSearch\Lucene\Search\Query\Boolean->rewrite(Object(ZendSearch\Lucene\Index))
#8 /var/www/html/statamic/vendor/zendframework/zendsearch/library/ZendSearch/Lucene/Index.php(669): ZendSearch\Lucene\Search\Query\Boolean->rewrite(Object(ZendSearch\Lucene\Index))
#9 /var/www/html/statamic/vendor/mmanos/laravel-search/src/Mmanos/Search/Index/Zend.php(177): ZendSearch\Lucene\Index->find(Object(ZendSearch\Lucene\Search\Query\Boolean))
#10 /var/www/html/statamic/vendor/mmanos/laravel-search/src/Mmanos/Search/Query.php(267): Mmanos\Search\Index\Zend->runQuery(Object(ZendSearch\Lucene\Search\Query\Boolean), Array)
#11 /var/www/html/statamic/core/API/Search.php(38): Mmanos\Search\Query->get()
#12 /var/www/html/statamic/bundles/Search/SearchTags.php(83): Statamic\API\Search::get('beer', NULL)
#13 /var/www/html/statamic/bundles/Search/SearchTags.php(60): Statamic\Addons\Search\SearchTags->buildSearchCollection()
#14 [internal function]: Statamic\Addons\Search\SearchTags->results()
#15 /var/www/html/statamic/core/View/Antlers/Engine.php(162): call_user_func(Array)
#16 [internal function]: Statamic\View\Antlers\Engine::renderTag('search', Array, '\n\n\t{{ if no_res...', Array)
#17 /var/www/html/statamic/core/View/Antlers/Parser.php(501): call_user_func_array(Array, Array)
#18 /var/www/html/statamic/core/View/Antlers/Parser.php(111): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="mdl...', Array, Array)
#19 /var/www/html/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('<div class="mdl...', Array, Array, false)
#20 /var/www/html/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('\n<div class="md...', Array, Array)
#21 /var/www/html/statamic/core/View/Antlers/Engine.php(69): Statamic\API\Parse::template('\n<div class="md...', Array)
#22 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/var/www/html/s...', Array)
#23 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#24 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#25 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#26 /var/www/html/statamic/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#27 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#28 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(595): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#29 /var/www/html/statamic/core/Http/Controllers/StatamicController.php(213): response(Object(Illuminate\View\View))
#30 [internal function]: Statamic\Http\Controllers\StatamicController->index('search')
#31 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#32 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#33 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#34 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#40 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#41 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#42 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /var/www/html/statamic/core/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /var/www/html/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /var/www/html/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /var/www/html/statamic/core/Http/Middleware/Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /var/www/html/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#86 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#88 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#89 /var/www/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#90 /var/www/html/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
```

**Comment by jackmcdade** [comment]
Does it work when you disable the cache?

**Comment by brettdewoody** [comment]
Seems to still throw the error with `APP_STATIC_CACHING=false` too. Made sure to clear the cache. I have Google's Pagespeed module (`mod_pagespeed`) enabled on the site, though I don't think that's effecting it.

**Comment by jasonvarga** [comment]
Is your `local` folder `777` recursively? Looks like a file permission error.

**Comment by jackmcdade** [comment]
Are you still having an issue here?

**Comment by brettdewoody** [comment]
Resolved, a file permission issue if I remember correctly.
