### ISSUE TITLE
Logged errors re: logs and stache

### ISSUE THREAD

**Issue by dannyuk1982** [statamic/v2-hub#1082]
Every day I get these 3 errors logged. It doesn't seem to be breaking anything, but I'd like to know what is happening going forward, in case it is causing a problem I am not yet aware of.

```
[2016-11-02 17:05:03] production.ERROR: ErrorException: file_put_contents(/home/public_html/local/storage/framework/cache/stache/timestamps): failed to open stream: Permission denied in /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81 Stack trace: #0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/home/...', 81, Array) #1 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(81): file_put_contents('/home/...', '9999999999s:193...', 0) #2 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(102): Illuminate\Filesystem\Filesystem->put('/home/...', '9999999999s:193...') #3 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php(157): Illuminate\Cache\FileStore->put('stache::timesta...', '9999999999s:193...', 0) #4 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(184): Illuminate\Cache\FileStore->forever('stache::timesta...', '{"pages":{"page...') #5 [internal function]: Illuminate\Cache\Repository->forever('stache::timesta...', '{"pages":{"page...') #6 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php(318): call_user_func_array(Array, Array) #7 /home/public_html/statamic/core/API/Cache.php(27): Illuminate\Cache\CacheManager->__call('forever', Array) #8 /home/public_html/statamic/core/Stache/UpdateManager.php(144): Statamic\API\Cache::put('stache::timesta...', '{"pages":{"page...') #9 /home/public_html/statamic/core/Stache/UpdateManager.php(65): Statamic\Stache\UpdateManager->persistTimestamps() #10 /home/public_html/statamic/core/Stache/Manager.php(79): Statamic\Stache\UpdateManager->update() #11 /home/public_html/statamic/core/Providers/StacheServiceProvider.php(158): Statamic\Stache\Manager->update() #12 /home/public_html/statamic/core/Providers/StacheServiceProvider.php(140): Statamic\Providers\StacheServiceProvider->updateStache() #13 [internal function]: Statamic\Providers\StacheServiceProvider->boot(Object(Illuminate\Http\Request)) #14 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array) #15 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array) #16 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\StacheServiceProvider)) #17 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Statamic\Providers\StacheServiceProvider), 25) #18 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure)) #19 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot() #20 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Statamic\Application)) #21 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array) #22 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap() #23 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request)) #24 /home/public_html/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #25 {main} [] [] 
```

```
[2016-11-02 17:05:04] production.ERROR: UnexpectedValueException: The stream or file "/home/public_html/local/storage/logs/statamic-2016-11-02.log" could not be opened: failed to open stream: Permission denied in /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, Object(ErrorException), Array) #3 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\Logger->error(Object(ErrorException), Array) #4 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Log/Writer.php(113): Illuminate\Log\Writer->writeLog('error', Object(ErrorException), Array) #5 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(50): Illuminate\Log\Writer->error(Object(ErrorException)) #6 /home/public_html/statamic/core/Exceptions/Handler.php(48): Illuminate\Foundation\Exceptions\Handler->report(Object(ErrorException)) #7 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(269): Statamic\Exceptions\Handler->report(Object(ErrorException)) #8 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(89): Illuminate\Foundation\Http\Kernel->reportException(Object(ErrorException)) #9 /home/public_html/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request)) #10 {main} [] [] 
```

```
[2016-11-02 17:05:04] production.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Uncaught UnexpectedValueException: The stream or file "/home/public_html/local/storage/logs/statamic-2016-11-02.log" could not be opened: failed to open stream: Permission denied in /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array) #1 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array) #2 /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, Object(UnexpectedValueException), Array) #3 /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Log/Writer.php(202): Monolog\Logger->error(Object(UnexpectedValueException), Array) #4 /home//public_htm in /home/public_html/statamic/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107 Stack trace: #0 {main} [] [] 
```

There should not be a permission error with these files as they are created by Statamic surely?

**Comment by jackmcdade** [comment]
Can you make sure `local` is `chmod -R 777`?

**Comment by dannyuk1982** [comment]
It is, I have ran that several times - all 777. The logs that cannot be access are not 777 but are created by the apache user

**Comment by dannyuk1982** [comment]
Had loads of these again today - bizarrely the log created for today was 644 (which would be fine) but the user was `nobody` group `nobody` instead of the apache user. The log was created by statamic (well, I assume, it wasn't manually created) this morning.

**Comment by dannyuk1982** [comment]
More info on the first error:

```ERROR
[2016-11-05 01:27:06] production.ERROR: ErrorException: file_put_contents(/home/public_html/local/storage/framework/cache/stache/timestamps): failed to open stream: Permission denied in /home/public_html/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:81
```

In the httpd access log, each time I get this it coincides with this odd request

```
[05/Nov/2016:XX:XX:XX +0000] "GET / HTTP/1.0" 500 4558 "-" "-"
```

**Comment by jackmcdade** [comment]
Who's your host? Are they manipulating your permissions? I know Dreamhost does this - i get notifications occasionally for old client sites from pre-sass/less days.

**Comment by dannyuk1982** [comment]
Dediserve, it's a dedicated machine, i.e. CentOS 7 build with cPanel with literally one website on.

I think this bug needs closing though, as it did this for a few weeks and then stopped - I don't get it, but who cares, it seems to have gone!
