### ISSUE TITLE
Problem saving child entries "There was a problem saving the data."

### ISSUE THREAD

**Issue by brianyuen** [statamic/v2-hub#1105]
### Expected behaviour
Attempting to save a child entry produces an error

### Actual behaviour
Getting an error reading "There was a problem saving the data. Please check your logs."

### Steps to reproduce
1.  Create page
2.  Add page under parent entry
3.  Edit child entry will get error
4. Moving page out from under parent and making the edit in CP saves successfully
5. Video of issue: https://cloudup.com/cTEvcCa2iPr

### Server configuration
**Operating system**:
Linux

**Web server:**

**PHP version:**

**Statamic version:**
2.1.17

**Updated from an older Statamic or fresh install:**
Fresh

**List of installed addons:**
None

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
Add those logs here
```
[2016-11-14 19:32:06] dev.ERROR: exception 'Statamic\Exceptions\FileNotFoundException' with message 'Fieldset(s) not found: [tbi]' in /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/API/Fieldset.php:55
Stack trace:
#0 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Data/Pages/Page.php(451): Statamic\API\Fieldset::get('tbi')
#1 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Data/Content/Content.php(280): Statamic\Data\Pages\Page->getFieldset()
#2 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/CP/Publish/Publisher.php(131): Statamic\Data\Content\Content->fieldset()
#3 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/CP/Publish/Publisher.php(93): Statamic\CP\Publish\Publisher->appendFieldset()
#4 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Controllers/PublishController.php(433): Statamic\CP\Publish\Publisher->publish()
#5 [internal function]: Statamic\Http\Controllers\PublishController->save()
#6 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#7 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('save', Array)
#8 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), 'save')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#14 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'save')
#15 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'save')
#16 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#17 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#20 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#23 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Middleware/Outpost.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#26 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#33 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#34 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#35 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#36 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#40 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/Http/Middleware/Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#69 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#70 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#71 /var/www/vhosts/indigo.domain.com/neurology.ucsf/root/index.php(156): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#72 {main}  
[2016-11-14 19:47:07] dev.ERROR: Cannot render an array variable as a string: {{ link }}  
[2016-11-14 19:47:13] dev.ERROR: Cannot render an array variable as a string: {{ link }}

**Comment by brianyuen** [comment]
Solved: Issue was with parent entry not having correct fieldset associated with it
