### ISSUE TITLE
Using the search feature throws a RuntimeException: Index is under processing now

### ISSUE THREAD

**Issue by heisRichard** [statamic/v2-hub#1107]
### Expected behaviour
When insert a string such as "fire" into the search input field (and pressing enter) I expect to be shown the results of that search. When I first installed Statamic the search was working (Redwood theme) although I am pretty sure I was getting multiple results. i.e One successful entry found, the result would be the same entry twice. I have since duplicated that theme, renamed it, worked on it (modified).

### Actual behaviour
Instead of showing the results page, I am shown an error page "Whoops, looks like something went wrong." With two errors.

1/1 -- RuntimeException in Index.php line 137: Index is under processing now
2/2 -- RuntimeException in Index.php line 154: Index is under processing now

### Steps to reproduce
1.  Enter a search term of "fire"
2.  Press enter
3.  Cry as you see an error screen...

### Server configuration
Windows 10

**Web server:**
WAMP

**PHP version:**
7.0.4

**Statamic version:**
2.1.17

**Updated from an older Statamic or fresh install:**
Fresh, but has been downgraded and reupgraded. Seperate issue of the settings tab being unavailable.

**List of installed addons:**
Emd's PowerTools

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
`[20:14:24] LOG.error: ZendSearch\Lucene\Exception\RuntimeException: Index is under processing now in C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Index.php:137
Stack trace:
#0 C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Index.php(382): ZendSearch\Lucene\Index::getActualGeneration(Object(ZendSearch\Lucene\Storage\Directory\Filesystem))
#1 C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Lucene.php(56): ZendSearch\Lucene\Index->__construct('C:\\wamp\\www\\rw2...', true)
#2 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Index\Zend.php(61): ZendSearch\Lucene\Lucene::create('C:\\wamp\\www\\rw2...')
#3 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Index\Zend.php(177): Mmanos\Search\Index\Zend->getIndex()
#4 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Query.php(267): Mmanos\Search\Index\Zend->runQuery(Object(ZendSearch\Lucene\Search\Query\Boolean), Array)
#5 C:\wamp\www\rw2016\statamic\core\API\Search.php(38): Mmanos\Search\Query->get()
#6 C:\wamp\www\rw2016\statamic\bundles\Search\SearchTags.php(83): Statamic\API\Search::get('fire', NULL)
#7 C:\wamp\www\rw2016\statamic\bundles\Search\SearchTags.php(60): Statamic\Addons\Search\SearchTags->buildSearchCollection()
#8 [internal function]: Statamic\Addons\Search\SearchTags->results()
#9 C:\wamp\www\rw2016\statamic\core\View\Antlers\Engine.php(162): call_user_func(Array)
#10 [internal function]: Statamic\View\Antlers\Engine::renderTag('search', Array, '\n\t\t\t{{ if no_re...', Array)
#11 C:\wamp\www\rw2016\statamic\core\View\Antlers\Parser.php(501): call_user_func_array(Array, Array)
#12 C:\wamp\www\rw2016\statamic\core\View\Antlers\Parser.php(111): Statamic\View\Antlers\Parser->parseCallbackTags('<section class=...', Array, Array)
#13 C:\wamp\www\rw2016\statamic\core\View\Antlers\Template.php(32): Statamic\View\Antlers\Parser->parse('<section class=...', Array, Array, false)
#14 C:\wamp\www\rw2016\statamic\core\API\Parse.php(22): Statamic\View\Antlers\Template::parse('<section class=...', Array, Array)
#15 C:\wamp\www\rw2016\statamic\core\View\Antlers\Engine.php(69): Statamic\API\Parse::template('<section class=...', Array)
#16 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(147): Statamic\View\Antlers\Engine->get('C:\\wamp\\www\\rw2...', Array)
#17 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(118): Illuminate\View\View->getContents()
#18 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(83): Illuminate\View\View->renderContents()
#19 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Http\Response.php(51): Illuminate\View\View->render()
#20 C:\wamp\www\rw2016\statamic\vendor\symfony\http-foundation\Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#21 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#22 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(595): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#23 C:\wamp\www\rw2016\statamic\core\Http\Controllers\StatamicController.php(213): response(Object(Illuminate\View\View))
#24 [internal function]: Statamic\Http\Controllers\StatamicController->index('search')
#25 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#26 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#27 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#28 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#34 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#35 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#36 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 C:\wamp\www\rw2016\statamic\core\StaticCaching\Middleware\Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\wamp\www\rw2016\statamic\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#53 C:\wamp\www\rw2016\statamic\core\Http\Middleware\PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#56 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#59 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#62 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#65 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#68 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#71 C:\wamp\www\rw2016\statamic\core\Http\Middleware\Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#74 C:\wamp\www\rw2016\statamic\core\StaticCaching\Middleware\Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#77 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#80 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#82 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#83 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#84 C:\wamp\www\rw2016\index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#85 {main}

Next ZendSearch\Lucene\Exception\RuntimeException: Index is under processing now in C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Index.php:154
Stack trace:
#0 C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Index.php(382): ZendSearch\Lucene\Index::getActualGeneration(Object(ZendSearch\Lucene\Storage\Directory\Filesystem))
#1 C:\wamp\www\rw2016\statamic\vendor\zendframework\zendsearch\library\ZendSearch\Lucene\Lucene.php(56): ZendSearch\Lucene\Index->__construct('C:\\wamp\\www\\rw2...', true)
#2 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Index\Zend.php(61): ZendSearch\Lucene\Lucene::create('C:\\wamp\\www\\rw2...')
#3 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Index\Zend.php(177): Mmanos\Search\Index\Zend->getIndex()
#4 C:\wamp\www\rw2016\statamic\vendor\mmanos\laravel-search\src\Mmanos\Search\Query.php(267): Mmanos\Search\Index\Zend->runQuery(Object(ZendSearch\Lucene\Search\Query\Boolean), Array)
#5 C:\wamp\www\rw2016\statamic\core\API\Search.php(38): Mmanos\Search\Query->get()
#6 C:\wamp\www\rw2016\statamic\bundles\Search\SearchTags.php(83): Statamic\API\Search::get('fire', NULL)
#7 C:\wamp\www\rw2016\statamic\bundles\Search\SearchTags.php(60): Statamic\Addons\Search\SearchTags->buildSearchCollection()
#8 [internal function]: Statamic\Addons\Search\SearchTags->results()
#9 C:\wamp\www\rw2016\statamic\core\View\Antlers\Engine.php(162): call_user_func(Array)
#10 [internal function]: Statamic\View\Antlers\Engine::renderTag('search', Array, '\n\t\t\t{{ if no_re...', Array)
#11 C:\wamp\www\rw2016\statamic\core\View\Antlers\Parser.php(501): call_user_func_array(Array, Array)
#12 C:\wamp\www\rw2016\statamic\core\View\Antlers\Parser.php(111): Statamic\View\Antlers\Parser->parseCallbackTags('<section class=...', Array, Array)
#13 C:\wamp\www\rw2016\statamic\core\View\Antlers\Template.php(32): Statamic\View\Antlers\Parser->parse('<section class=...', Array, Array, false)
#14 C:\wamp\www\rw2016\statamic\core\API\Parse.php(22): Statamic\View\Antlers\Template::parse('<section class=...', Array, Array)
#15 C:\wamp\www\rw2016\statamic\core\View\Antlers\Engine.php(69): Statamic\API\Parse::template('<section class=...', Array)
#16 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(147): Statamic\View\Antlers\Engine->get('C:\\wamp\\www\\rw2...', Array)
#17 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(118): Illuminate\View\View->getContents()
#18 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\View.php(83): Illuminate\View\View->renderContents()
#19 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Http\Response.php(51): Illuminate\View\View->render()
#20 C:\wamp\www\rw2016\statamic\vendor\symfony\http-foundation\Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#21 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#22 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php(595): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#23 C:\wamp\www\rw2016\statamic\core\Http\Controllers\StatamicController.php(213): response(Object(Illuminate\View\View))
#24 [internal function]: Statamic\Http\Controllers\StatamicController->index('search')
#25 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(256): call_user_func_array(Array, Array)
#26 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#27 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#28 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#34 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#35 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#36 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 C:\wamp\www\rw2016\statamic\core\StaticCaching\Middleware\Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#46 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Routing\Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#47 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#49 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 C:\wamp\www\rw2016\statamic\vendor\barryvdh\laravel-debugbar\src\Middleware\Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#53 C:\wamp\www\rw2016\statamic\core\Http\Middleware\PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#56 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#59 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#62 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#65 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#68 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#71 C:\wamp\www\rw2016\statamic\core\Http\Middleware\Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#74 C:\wamp\www\rw2016\statamic\core\StaticCaching\Middleware\Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#77 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(124): call_user_func_array(Array, Array)
#80 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#82 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#83 C:\wamp\www\rw2016\statamic\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#84 C:\wamp\www\rw2016\index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#85 {main}
`
````

**Comment by jackmcdade** [comment]
We can't recreate this no matter what we try. Is there anything you can do to help?
