### ISSUE TITLE
Update from 2.1.19 to 2.5.1 did not convert all taxonomies properly.

### ISSUE THREAD

**Issue by warkior** [statamic/v2-hub#1200]
### Expected behaviour
The upgrade should have left the site functioning as it was before, but faster and better. :)

### Actual behaviour
Tags were only partially converted to the new format. The files for tags were changed but the references to them in some collection entries were not modified.
ie:
http://s.warkior.com/tags_1E3BDB05.png

NOW, when viewing the list of tags on the site in the CP I see the following:
http://s.warkior.com/taxonomies_in_tags_1E3BDD5B.png

### Steps to reproduce
1.  Ran upgrade from 2.1.19 to 2.5.1.
2.  Problem was found.
3.  Ran housekeeping task.
4. Problem remains.

### Server configuration
**Operating system**: 
Mac OS

**Web server:** 
Valet

**PHP version:** 
7.0

**Statamic version:** 
2.1.19 -> 2.5.1

**Updated from an older Statamic or fresh install:** 
Updated

**List of installed addons:** 
Several in-house plugins.

**Comment by jackmcdade** [comment]
Was your Taxonomy name called `Tags` specifically, or was it perhaps `Tag`?

**Comment by edalzell** [comment]
I had this happen to me too but assumed it was because I had duplicate slugs (but diff ids) in some old data. Perhaps that wasn't the case?

**Comment by jasonvarga** [comment]
Take one of the IDs that are leftover after to 2.5. Is there a corresponding term in 2.1?

**Comment by warkior** [comment]
At @jasonvarga 's advice, I tried the install again, this time manually, and it seems to have resolved this issue.

**Comment by warkior** [comment]
@jasonvarga asked for some additional logs, here's some of what I found...

```
[2017-01-27 18:59:11] local.ERROR: Symfony\Component\Debug\Exception\FatalErrorException: Maximum execution time of 30 seconds exceeded in /HIDDEN/
statamic/vendor/league/flysystem/src/Adapter/Local.php:261

[2017-01-27 20:09:59] local.DEBUG: There was a problem adding taxonomy terms to data with ID 75026c43-7ce7-4fc7-bfa7-31d412d76a3b  
[2017-01-27 20:09:59] local.DEBUG: Passed value cannot be an array
#0 /HIDDEN/statamic/vendor/danielstjules/stringy/src/Stringy.php(65): Stringy\Stringy->__construct(Array, NULL)
#1 /HIDDEN/statamic/vendor/danielstjules/stringy/src/StaticStringy.php(383): Stringy\Stringy::create(Array)
#2 /HIDDEN/statamic/bootstrap/helpers.php(472): Stringy\StaticStringy::slugify(Array)
#3 /HIDDEN/statamic/core/API/Term.php(127): slugify(Array)
#4 /HIDDEN/statamic/core/Stache/Staches/TaxonomyStache.php(77): Statamic\API\Term::normalizeSlug(Array)
#5 [internal function]: Statamic\Stache\Staches\TaxonomyStache->Statamic\Stache\Staches\{closure}(Array, 0)
#6 /HIDDEN/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(469): array_map(Object(Closure), Array, Array)
#7 /HIDDEN/statamic/core/Stache/Staches/TaxonomyStache.php(78): Illuminate\Support\Collection->map(Object(Closure))
#8 /HIDDEN/statamic/core/Data/Taxonomies/TermTracker.php(83): Statamic\Stache\Staches\TaxonomyStache->syncAssociations('75026c43-7ce7-4...', 'tags', Object(Illuminate\Support\Collection))

[2017-01-27 20:38:08] local.ERROR: ErrorException: include(/HIDDEN/statamic/vendor/laravel/framework/src/Illuminate/Support/Facades/Log.php): failed to open stream: Too many open files in /HIDDEN/statamic/vendor/composer/ClassLoader.php:412
Stack trace:
#0 /HIDDEN/statamic/vendor/composer/ClassLoader.php(412): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(/Users/...', '/Users/jamesw/s...', 412, Array)
#1 /HIDDEN/statamic/vendor/composer/ClassLoader.php(412): include()
#2 /HIDDEN/statamic/vendor/composer/ClassLoader.php(301): Composer\Autoload\includeFile('/Users/jamesw/s...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Supp...')
#4 [internal function]: spl_autoload_call('Illuminate\\Supp...')

[2017-01-27 20:18:13] local.ERROR: ErrorException: unserialize(): Error at offset 2 of 8182 bytes in /HIDDEN/statamic/vendor/laravel/framework/src/Illuminate/Cache/FileStore.php:78

```

**Comment by jackmcdade** [comment]
Thanks! It definitely seems to be stemming from max script time.
