### ISSUE TITLE
500 error in asset modal for S3 assets with spaces in file name

### ISSUE THREAD

**Issue by jeffmckeand** [statamic/v2-hub#1241]
### Expected behaviour
Asset modal should load for S3 assets with spaces in file name, as it does with files that don't contain spaces (see attached gif)

### Actual behaviour
When loading asset modal for S3 assets with spaces in the file name, loading spinner persists and console shows 500 error

![s3-filename-error](https://cloud.githubusercontent.com/assets/713259/22595840/c115e26c-e9ee-11e6-8450-eac0394afe64.gif)

### Steps to reproduce
1.  Add asset to S3 container with spaces in the file name
2.  Attempt to edit the asset with spaces in the file name
3.  Get error

### Server configuration
**Operating system**:
macOS Sierra 10.12.4 beta

**Web server:**
Homebrew apache

**PHP version:**
7.1.1

**Statamic version:**
2.5.2

**Updated from an older Statamic or fresh install:**
Updated from 2.1.19

**List of installed addons:**
Google Maps 1.02
SVG Output 1.0.0
Taxonomy Slug Filter 1.1.0
Tel 1.1

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
[2017-02-03 14:39:53] local.ERROR: ErrorException: getimagesize(https://s3.amazonaws.com/nbccweb/misc/asset with spaces.jpeg): failed to open stream: HTTP request failed! HTTP/1.1 505 HTTP Version not supported
 in /Users/jmckeand/Sites/nbccweb/statamic/core/Assets/DimensionBuilder.php:110
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'getimagesize(ht...', '/Users/jmckeand...', 110, Array)
#1 /Users/jmckeand/Sites/nbccweb/statamic/core/Assets/DimensionBuilder.php(110): getimagesize('https://s3.amaz...')
#2 /Users/jmckeand/Sites/nbccweb/statamic/core/Assets/DimensionBuilder.php(52): Statamic\Assets\DimensionBuilder->getImageDimensions('https://s3.amaz...')
#3 /Users/jmckeand/Sites/nbccweb/statamic/core/Assets/DimensionBuilder.php(66): Statamic\Assets\DimensionBuilder->dimensions()
#4 /Users/jmckeand/Sites/nbccweb/statamic/core/Assets/Asset.php(376): Statamic\Assets\DimensionBuilder->width()
#5 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Controllers/AssetsController.php(377): Statamic\Assets\Asset->width()
#6 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Controllers/AssetsController.php(182): Statamic\Http\Controllers\AssetsController->supplementAssetForEditing(Object(Statamic\Assets\Asset))
#7 [internal function]: Statamic\Http\Controllers\AssetsController->edit('s3', 'misc/asset with...')
#8 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#9 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('edit', Array)
#10 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), 'edit')
#11 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#14 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#15 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#16 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'edit')
#17 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'edit')
#18 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#19 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#20 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#22 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Middleware/Outpost.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /Users/jmckeand/Sites/nbccweb/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /Users/jmckeand/Sites/nbccweb/statamic/core/Http/Middleware/Glide.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 /Users/jmckeand/Sites/nbccweb/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#71 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#72 /Users/jmckeand/Sites/nbccweb/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#73 /Users/jmckeand/Sites/nbccweb/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#74 {main}  
```

**Comment by jeffmckeand** [comment]
Still an issue in 2.5.10. Would only be partially addressed by #1263, which does not account for filenames with spaces for files that were added to S3 through some other means, like Transmit.
