### ISSUE TITLE
Cannot create fieldset in 2.5.7 on production site

### ISSUE THREAD

**Issue by funkatron** [statamic/v2-hub#1366]
### Expected behaviour
I should be able to click on "Create Fieldset" in /cp/fieldsets and get the form to create a fieldset

### Actual behaviour
I just get a spinner, no form ever appears

### Steps to reproduce
1.  Go to  /cp/fieldsets
2.  Click on Create Fieldset

### Server configuration
**Operating system**:
Ubuntu 16.04.2 LTS

**Web server:**
nginx/1.10.0

**PHP version:**
PHP 7.0.17-2+deb.sury.org~xenial+1

**Statamic version:**
2.5.7

**Updated from an older Statamic or fresh install:**
Updated from older (2.5.3)

**List of installed addons:**
n/a

**NOTE** This works fine on my local dev using the php dev server. I suspect it may be an nginx config issue. Config for my site follows

```
server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;

    root /var/www/DOMAIN.FOO/public;
    index index.php index.html index.htm;

    server_name *.osmihelp.org osmihelp.org;

    ssl_certificate /etc/letsencrypt/live/DOMAIN.FOO/cert.pem;
    ssl_certificate_key /etc/letsencrypt/live/DOMAIN.FOO/privkey.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;

    try_files $uri /index.php;

    error_page 404 /404.html;
    error_page 500 502 503 504 /50x.html;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    if ($scheme != "https") {
        return 301 https://$host$request_uri;
    }
}
```

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
[2017-04-02 20:18:59] dev.ERROR: Statamic\Exceptions\FileNotFoundException: Fieldset(s) not found: [create] in /var/www/osmihelp.org/public/statamic/core/API/Fieldset.php:55
Stack trace:
#0 /var/www/osmihelp.org/public/statamic/core/Http/Controllers/FieldsetController.php(100): Statamic\API\Fieldset::get('create', 'default')
#1 [internal function]: Statamic\Http\Controllers\FieldsetController->getFieldset('create')
#2 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#3 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('getFieldset', Array)
#4 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\FieldsetController), Object(Illuminate\Routing\Route), 'getFieldset')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\FieldsetController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'getFieldset')
#11 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'getFieldset')
#12 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#13 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /var/www/osmihelp.org/public/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 /var/www/osmihelp.org/public/statamic/core/Http/Middleware/Outpost.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 /var/www/osmihelp.org/public/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#28 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#29 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#30 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /var/www/osmihelp.org/public/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#36 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /var/www/osmihelp.org/public/statamic/core/Http/Middleware/Glide.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /var/www/osmihelp.org/public/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#63 /var/www/osmihelp.org/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#64 /var/www/osmihelp.org/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#65 {main}
```

**Comment by jackmcdade** [comment]
This almost seems like the app is missing core files. Can you try downloading a fresh copy of 2.5.7 and replacing the core `/statamic` folder?

**Comment by funkatron** [comment]
WIll try. Also, here's what's in the Fieldset directory
http://img.spz.im/XuKH3M3B.png. Anything missing?

**Comment by funkatron** [comment]
The Controller for Fieldsets is there. Now I wonder if somehow it's being routed incorrectly. I'm not intimately familiar with the codebase but can make things happen if you give me a pointer.

```
osmi@osmi-www:/var/www/osmihelp.org/public/statamic$ cat core/Http/Controllers/FieldsetController.php
```

```php
<?php

namespace Statamic\Http\Controllers;

use Statamic\API\Config;
use Statamic\API\Fieldset;
use Statamic\API\Folder;
use Statamic\API\Helper;
use Statamic\API\Str;
use Statamic\API\Pattern;
use Statamic\API\Taxonomy;
use Statamic\CP\FieldtypeFactory;
use Illuminate\Support\Collection;

class FieldsetController extends CpController
{
    /**
     * List all fieldsets
     *
     * @return \Illuminate\View\View
     */
    public function index()
    {
        $data = [
            'title' => 'Fieldsets'
        ];

        return view('fieldsets.index', $data);
    }

    public function get()
    {
        $fieldsets = [];

        foreach (Fieldset::all() as $fieldset) {
            // If we've decided to omit hidden fieldsets, and this one should be
            // hidden, we'll just move right along.
            if (bool($this->request->query('hidden', true)) === false && $fieldset->hidden()) {
                continue;
            }

            $fieldsets[] = [
                'title'    => $fieldset->title(),
                'id'       => $fieldset->name(), // vue uses this as an id
                'uuid'     => $fieldset->name(), // keeping this here temporarily, just in case.
                'edit_url' => $fieldset->editUrl()
            ];
        }

        return ['columns' => ['title'], 'items' => $fieldsets];
    }

    /**
     * @param string $name
     * @return \Illuminate\View\View
     */
    public function edit($name)
    {
        $fieldset = Fieldset::get($name);

        $title = 'Editing ' . $name . '.yaml';

        return view('fieldsets.edit', compact('title', 'fieldset'));
    }

    /**
     * Delete a fieldset
     *
     * @return array
     */
    public function delete()
    {
        $ids = Helper::ensureArray($this->request->input('ids'));

        foreach ($ids as $name) {
            $fieldset = Fieldset::get($name);
            $fieldset->delete();
        }

        return ['success' => true];
    }

    public function getFieldset($fieldset)
    {
        $type = 'default';

        if (substr_count($fieldset, '.') === 2) {
            // addon fieldsets
            list($type, $addon, $name) = explode('.', $fieldset);
            $fieldset = $addon.'.'.$name;
        } elseif (substr_count($fieldset, '.') === 1) {
            // settings fieldsets
            list($type, $fieldset) = explode('.', $fieldset);
        }

        // Create a temporary fieldset for when creating.
        if ($fieldset === 'create' && $this->request->creating) {
            $fieldset = Fieldset::create('temporary');
        } else {
            $fieldset = Fieldset::get($fieldset, $type);
        }

        $fieldset->locale($this->request->input('locale', default_locale()));

        try {
            $array = $fieldset->toArray(bool($this->request->input('partials', true)));
        } catch (\Exception $e) {
            return response(['success' => false, 'message' => $e->getMessage()], 500);
        }

        if ($fieldset->name() === 'user') {
            // If logging in using emails, make sure there is no username field.
            if (Config::get('users.login_type') === 'email') {
                $array['fields'] = collect($array['fields'])->reject(function ($field) {
                    return $field['name'] === 'username';
                })->values()->all();
            }
        }

        // Default types of fieldsets should have their taxonomies formatted ready for the fields builder
        if ($fieldset->type() === 'default' && $this->request->editing) {
            $array['taxonomies'] = $this->formatTaxonomiesForEditing(
                array_get($array, 'taxonomies')
            );
        }

        return $array;
    }

    /**
     * Format taxonomies for editing
     *
     * Taxonomies exist in the fieldset file in one format, but the Vue component used
     * for editing them requires them in another format.
     *
     * @param array $array
     * @return array
     */
    private function formatTaxonomiesForEditing($array)
    {
        $taxonomies = collect();

        foreach (Taxonomy::all() as $handle => $taxonomy) {
            // Since we're adding all the taxonomies to the response, we'll
            // need another way to know which should and shouldn't be there.
            $hidden = false;

            // If *any* taxonomies have been defined, *and* the currently iterated taxonomy is not found,
            // we want to mark it as hidden. We check for *any* taxonomies being defined because if it's
            // completely empty, then *all* taxonomies should be shown.
            if (! is_null($array) && ! isset($array[$handle])) {
                $hidden = true;
            }

            $config = array_get($array, $handle, []);

            // Taxonomies can be defined by simply adding "true".
            $config = ($config === true) ? [] : $config;

            $defaults = [
                'taxonomy' => $handle,
                'display' => $taxonomy->title(),
                'hidden' => $hidden
            ];

            $taxonomies[$handle] = array_merge($defaults, $config);
        }

        // Sort the fields by the order in which they were provided.
        if (! empty($array)) {
            $taxonomies = $taxonomies->sortBy(function ($arr) use ($array, $taxonomies) {
                $handle = $arr['taxonomy'];

                // If the taxonomy was not provided, put it at the end.
                if (! isset($array[$handle])) {
                    return count($taxonomies);
                }

                return array_search($handle, array_keys($array));
            });
        }

        return $taxonomies->values()->all();
    }

    public function fieldtypes()
    {
        $fieldtypes = [];

        foreach ($this->getAllFieldtypes() as $fieldtype) {
            $config = [];

            foreach ($fieldtype->getConfigFieldset()->fieldtypes() as $item) {
                $c = $item->getFieldConfig();

                // Go through each fieldtype in *its* config fieldset and process the values. SO META.
                foreach ($item->getConfigFieldset()->fieldtypes() as $field) {
                    if (! in_array($field->getName(), array_keys($c))) {
                        continue;
                    }

                    $c[$field->getName()] = $field->preProcess($c[$field->getName()]);
                }

                $c['display'] = trans("fieldtypes/{$fieldtype->snakeName()}.{$c['name']}");
                $c['instructions'] = markdown(trans("fieldtypes/{$fieldtype->snakeName()}.{$c['name']}_instruct"));

                $config[] = $c;
            }

            $fieldtypes[] = [
                'label' => $fieldtype->getAddonName(),
                'name' => $fieldtype->snakeName(),
                'canBeValidated' => $fieldtype->canBeValidated(),
                'canBeLocalized' => $fieldtype->canBeLocalized(),
                'canHaveDefault' => $fieldtype->canHaveDefault(),
                'config' => $config,
            ];
        }

        $hidden = ['replicator_sets', 'fields', 'asset_container', 'asset_folder', 'user_password',
                   'locale_settings', 'theme', 'redactor_settings', 'relate'];
        foreach ($fieldtypes as $key => $fieldtype) {
            if (in_array($fieldtype['name'], $hidden)) {
                unset($fieldtypes[$key]);
            }
        }

        return array_values($fieldtypes);
    }

    /**
     * @return \Illuminate\Support\Collection
     */
    private function getAllFieldtypes()
    {
        return collect([bundles_path(), addons_path()])->flatMap(function ($path) {
            return Folder::getFilesRecursively($path);
        })->filter(function ($path) {
            return Pattern::endsWith($path, 'Fieldtype.php');
        })->map(function ($path) {
            $name = str_replace('Fieldtype', '', basename($path, '.php'));
            return resource_loader()->loadFieldtype($name);
        })->sortBy(function ($fieldtype) {
            return $fieldtype->getAddonName();
        });
    }

    public function update($name)
    {
        $contents = $this->request->input('fieldset');

        $fieldset = $this->prepareFieldset($name, $contents);

        $fieldset->save();

        $this->success(translate('cp.fieldset_updated'));

        return [
            'success' => true,
            'redirect' => route('fieldset.edit', $fieldset->name())
        ];
    }

    private function process($fields, $fallback_type = 'text')
    {
        // Go through each field in the fieldset
        foreach ($fields as $field_name => $field_config) {
            // Get the config fieldset for that field's fieldtype. Still with me?
            $type = array_get($field_config, 'type', $fallback_type);
            $fieldtype = FieldtypeFactory::create($type);
            $fieldtypes = $fieldtype->getConfigFieldset()->fieldtypes();

            // Go through each fieldtype in the config fieldset and process the values.
            foreach ($fieldtypes as $k => $field) {
                // If a non-array is encountered, it's probably a "handle: true" used in the "taxonomies" section.
                if (! is_array($field_config)) {
                    continue;
                }

                if (! in_array($field->getName(), array_keys($field_config))) {
                    continue;
                }

                $fields[$field_name][$field->getName()] = $field->process($fields[$field_name][$field->getName()]);
            }
        }

        return $fields;
    }

    public function updateLayout($fieldset)
    {
        $layout = collect($this->request->input('fields'))->keyBy('name')->toArray();

        $fieldset = Fieldset::get($fieldset);

        $contents = $fieldset->contents();

        $fields = array_get($contents, 'fields', []);

        $title_field = $fields['title'];

        $updated_fields = [];

        foreach ($layout as $name => $item) {
            $field = $fields[$name];

            if (isset($item['width'])) {
                $field['width'] = $item['width'];
            }

            $updated_fields[$name] = $field;
        }

        // Put back the title field at the front.
        $updated_fields = array_merge(['title' => $title_field], $updated_fields);

        $contents['fields'] = $updated_fields;

        $fieldset->contents($contents);

        $fieldset->save();
    }

    public function create()
    {
        return view('fieldsets.create', [
            'title' => 'Create fieldset'
        ]);
    }

    public function store()
    {
        $contents = $this->request->input('fieldset');

        $slug = $this->request->has('slug')
            ? $this->request->input('slug')
            : Str::slug(array_get($contents, 'title'), '_');

        $fieldset = $this->prepareFieldset($slug, $contents);

        $fieldset->save();

        $this->success(translate('cp.fieldset_created'));

        return [
            'success' => true,
            'redirect' => route('fieldset.edit', $fieldset->name())
        ];
    }

    /**
     * Quickly create a new barebones fieldset from within the fieldtype
     *
     * @return array
     */
    public function quickStore()
    {
        $title = $this->request->name;
        $name = Str::slug($title, '_');

        if (Fieldset::exists($name)) {
            return ['success' => true];
        }

        $fieldset = Fieldset::create($name);
        $fieldset->title($title);
        $fieldset->save();

        return ['success' => true];
    }

    private function prepareFieldset($slug, $contents)
    {
        // We need to key the array by name
        $fields = [];
        foreach ($contents['fields'] as $field) {
            $field_name = $field['name'];
            unset($field['name']);
            $fields[$field_name] = $field;
        }

        $contents['fields'] = $this->process($fields);

        $contents['taxonomies'] = $this->processTaxonomies($contents['taxonomies']);

        $fieldset = Fieldset::create($slug, $contents);

        return $fieldset;
    }

    /**
     * Process taxonomies
     *
     * The "taxonomies" key of the fieldset will be submitted differently than
     * should be saved. It also needs to be ran through the fieldtype processor.
     *
     * @param array $taxonomies
     * @return array
     */
    private function processTaxonomies($taxonomies)
    {
        $taxonomies = collect($taxonomies)->reject(function ($item) {
            return $item['hidden'] === true;
        })->keyBy('taxonomy')->map(function ($item, $handle) {
            unset($item['hidden'], $item['taxonomy']);

            if ($item['display'] === Taxonomy::whereHandle($handle)->title()) {
                unset($item['display']);
            }

            $item = array_filter($item);

            // Visible taxonomy fields with no configuration are specified by "true"
            if (empty($item)) {
                return true;
            }

            return $item;
        });

        // If everything should be hidden, we specify that with "false"
        if ($taxonomies->isEmpty()) {
            return false;
        }

        return $this->process($taxonomies->all(), 'taxonomy');
    }
}

**Comment by jasonvarga** [comment]
Resolved outside of github. The problem was the index.php rewrite rule in the nginx conf wasn't passing along the query string. I'm sure creating fieldsets wasn't the only thing that was broken.
