### ISSUE TITLE
Can't save system settings after changing url to ENV

### ISSUE THREAD

**Issue by Rias500** [statamic/v2-hub#1374]
### Expected behaviour
Saving the system settings in the control panel works.

### Actual behaviour
The control panel gives an error

### Steps to reproduce
1.  Change the locales in system.yaml to get the url from an environment variable

```
locales:
  en:
    full: en
    name: English
    url: '{env:APP_URL}'
```

2.  Try to save system settings in the control panel
3.  Error

### Logs
If any logs (browser, server, or Statamic) are appropriate...
<details>
```

[2017-04-07 14:26:20] dev.ERROR: ErrorException: Undefined index: raw in /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Controllers/SettingsController.php:56
Stack trace:
#0 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Controllers/SettingsController.php(56): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/Users/rias/Cod...', 56, Array)
#1 [internal function]: Statamic\Http\Controllers\SettingsController->update('system')
#2 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#3 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('update', Array)
#4 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\SettingsController), Object(Illuminate\Routing\Route), 'update')
#5 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#6 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#8 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\SettingsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'update')
#11 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'update')
#12 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#13 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/CP/Configurable.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 [internal function]: Statamic\Http\Middleware\CP\Configurable->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#19 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#22 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/Outpost.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#25 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#32 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#33 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#34 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#35 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 /Users/rias/Code/statamic-boilerplate/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#38 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#39 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /Users/rias/Code/statamic-boilerplate/statamic/core/Http/Middleware/Glide.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /Users/rias/Code/statamic-boilerplate/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /Users/rias/Code/statamic-boilerplate/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#70 /Users/rias/Code/statamic-boilerplate/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#71 /Users/rias/.composer/vendor/laravel/valet/server.php(128): require('/Users/rias/Cod...')
#72 {main}  

```
</details>

**Comment by jasonvarga** [comment]
This appears to be resolved. Let us know if you're still running into this issue.

**Comment by mirill1** [comment]
I still have this issue.
Can't save the system settings from backend.
I'm getting the 'Undefined index: raw' error message.

system.yaml:
locales:
  de:
    name: Deutsch
    full: de_DE
    url: '{env:SITE_URL}'


Statamic: 2.9.6.
PHP 5.6.33

**Comment by jasonvarga** [comment]
Can you post your system.yaml and your .env? (with any sensitive values removed)

**Comment by jasonvarga** [comment]
The only way I can get this to happen is if I reference an environment variable that doesn't exist.

**Comment by mirill1** [comment]
**My .env:**
APP_ENV=development
APP_URL=https://XXX.de
SITE_URL=https://XXX.de
SITE_URL_EN=https://XXX.de
API_URL=https://XXX.de
HTTPS=on

**My system.yaml:**
license_key: XXX
locales:
  de:
    name: Deutsch
    full: de_DE
    url: '{env:SITE_URL}'
  en:
    full: en_US
    name: English
    url: '{env:SITE_URL_EN}'
timezone: UTC
date_format: F jS, Y
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
app_key: XXX
redactor:
  - 
    name: Standard
    settings:
      buttons:
        - formatting
        - bold
        - italic
        - link
        - unorderedlist
        - orderedlist
        - html
  - 
    name: Basic
    settings:
      buttons:
        - bold
        - italic
use_https: true
send_powered_by_header: true
ensure_unique_ids: false
yaml_parser: spyc

**Comment by wesort** [comment]
Just started a new site and I'm still seeing this issue. 

**Workaround**: manually edit `system.yaml` file. 

### `.env`
```
APP_ENV=dev
SITE_URL=https://example.com
```

<hr>

### `system.yaml`
```
app_key: XXXXXXXXX
yaml_parser: symfony
locales:
  en:
    full: en_GB
    name: English
    url: "{env:SITE_URL}"
license_key: XXX-XXX
timezone: UTC
date_format: j F Y
default_extension: md
filesystems:
  content:
    driver: local
    root: site/content
  storage:
    driver: local
    root: site/storage
  users:
    driver: local
    root: site/users
  themes:
    driver: local
    root: site/themes
    url: /site/themes
redactor:
  -
    name: Standard
    settings:
      buttons:
        - formatting
        - bold
        - italic
        - deleted
        - link
        - unorderedlist
        - orderedlist
        - html
      replaceDivs: false
csrf_exclude: [ ]
send_powered_by_header: true
ensure_unique_ids: false

```
