### ISSUE TITLE
Workshop doesn't wrap timestamp values in quotes

### ISSUE THREAD

**Issue by danielfowler** [statamic/v2-hub#1488]
### Expected behaviour
When I save a time field from a frontend Workshop form, I believe the resultant YAML should be `end_time: "18:00"`

### Actual behaviour
The resultant YAML is `end_time: 18:00`

### Steps to reproduce
1.  Create a `workshop:entry:create` form with `<input type="time">`
2.  Submit the form
3.  Observe the value saved

### Server Details

**Operating System**: Mac OS

**Web Server:** Apache

**PHP Version:** 7

**Statamic Version:** 2.5.3

**Updated from an older Statamic or fresh install:** updated

**List of installed addons:** Imgix, Loop, ParseURL, TaxonomyFilter, Workshop

### Logs

Several like this one:

<details>
```
production.ERROR: Exception: DateTime::__construct(): Failed to parse time string (major/tesol-colloquium/01) at position 0 (m): The timezone could not be found in the database in /www/COE_WEB/statamic/vendor/nesbot/carbon/src/Carbon/Carbon.php:221
Stack trace:
#0 /www/COE_WEB/statamic/vendor/nesbot/carbon/src/Carbon/Carbon.php(221): DateTime->__construct('major/tesol-col...', Object(DateTimeZone))
#1 /www/COE_WEB/statamic/vendor/nesbot/carbon/src/Carbon/Carbon.php(249): Carbon\Carbon->__construct('major/tesol-col...', NULL)
#2 /www/COE_WEB/statamic/core/Data/Entries/EntryCollection.php(55): Carbon\Carbon::parse('major/tesol-col...')
#3 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(659): Statamic\Data\Entries\EntryCollection->Statamic\Data\Entries\{closure}(Object(Statamic\Data\Entries\Entry))
#4 [internal function]: Illuminate\Support\Collection->Illuminate\Support\{closure}(Object(Statamic\Data\Entries\Entry))
#5 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(202): array_filter(Array, Object(Closure))
#6 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(660): Illuminate\Support\Collection->filter(Object(Closure))
#7 /www/COE_WEB/statamic/core/Data/Entries/EntryCollection.php(56): Illuminate\Support\Collection->reject(Object(Closure))
#8 /www/COE_WEB/statamic/bundles/Collection/CollectionTags.php(351): Statamic\Data\Entries\EntryCollection->removeBefore('major/tesol-col...')
#9 /www/COE_WEB/statamic/bundles/Collection/CollectionTags.php(311): Statamic\Addons\Collection\CollectionTags->filterSince()
#10 /www/COE_WEB/statamic/bundles/Collection/CollectionTags.php(104): Statamic\Addons\Collection\CollectionTags->filter()
#11 /www/COE_WEB/statamic/bundles/Collection/CollectionTags.php(80): Statamic\Addons\Collection\CollectionTags->collect(Object(Statamic\Data\Entries\EntryCollection))
#12 [internal function]: Statamic\Addons\Collection\CollectionTags->__call('events', Array)
#13 /www/COE_WEB/statamic/core/View/Antlers/Engine.php(162): call_user_func(Array)
#14 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n  {{ if no_res...', Array)
#15 /www/COE_WEB/statamic/core/View/Antlers/Parser.php(512): call_user_func_array(Array, Array)
#16 /www/COE_WEB/statamic/core/View/Antlers/Parser.php(112): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="row...', Array, Array)
#17 /www/COE_WEB/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('<div class="row...', Array, Array, false)
#18 /www/COE_WEB/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<div class="row...', Array, Array)
#19 /www/COE_WEB/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('<div class="row...', Array)
#20 [internal function]: Statamic\Addons\Partial\PartialTags->__call('calendar/list', Array)
#21 /www/COE_WEB/statamic/core/View/Antlers/Engine.php(162): call_user_func(Array)
#22 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial', Array, '', Array)
#23 /www/COE_WEB/statamic/core/View/Antlers/Parser.php(512): call_user_func_array(Array, Array)
#24 /www/COE_WEB/statamic/core/View/Antlers/Parser.php(112): Statamic\View\Antlers\Parser->parseCallbackTags('<!---->\n\n<div c...', Array, Array)
#25 /www/COE_WEB/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('<!---->\n\n<div c...', Array, Array, false)
#26 /www/COE_WEB/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<!--{{#\n{{ if g...', Array, Array)
#27 /www/COE_WEB/statamic/core/View/Antlers/Engine.php(69): Statamic\API\Parse::template('<!--{{#\n{{ if g...', Array)
#28 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/www/COE_WEB/si...', Array)
#29 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#30 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#31 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#32 /www/COE_WEB/statamic/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#33 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#34 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(595): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#35 /www/COE_WEB/statamic/core/Http/Controllers/StatamicController.php(213): response(Object(Illuminate\View\View))
#36 [internal function]: Statamic\Http\Controllers\StatamicController->index('events/major/te...')
#37 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#38 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#39 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#40 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#46 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#47 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#48 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /www/COE_WEB/statamic/core/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#57 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#58 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#59 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#61 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#62 /www/COE_WEB/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /www/COE_WEB/statamic/core/Http/Middleware/Glide.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 /www/COE_WEB/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#86 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#89 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#91 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#92 /www/COE_WEB/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#93 /www/COE_WEB/index.php(142): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#94 {main}  
```
</details>

**Comment by jasonvarga** [comment]
This is solved if you use `yaml_parser: symfony`.
