### ISSUE TITLE
SearchController toArray() on null exception

### ISSUE THREAD

**Issue by jackwakefield** [statamic/v2-hub#1837]
### Expected behaviour
I searched for a page in the control panel using the global search in the header, which threw the following exception:

```Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function toArray() on null
#79 core/Http/Controllers/SearchController.php(59): search
#78 core/Http/Controllers/SearchController.php(0): call_user_func_array
#77 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): callAction
#76 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): call
#75 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\{closure}
#74 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(0): call_user_func
#73 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Pipeline\{closure}
#72 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(0): call_user_func
#71 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#70 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): callWithinStack
#69 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): dispatch
#68 vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): runWithCustomDispatcher
#67 vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): run
#66 vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\{closure}
#65 vendor/laravel/framework/src/Illuminate/Routing/Router.php(0): call_user_func
#64 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Pipeline\{closure}
#63 core/Http/Middleware/CP/Authenticate.php(62): handle
#62 core/Http/Middleware/CP/Authenticate.php(0): call_user_func_array
#61 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#60 core/Http/Middleware/Outpost.php(48): handle
#59 core/Http/Middleware/Outpost.php(0): call_user_func_array
#58 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#57 core/Http/Middleware/CP/Localize.php(25): handle
#56 core/Http/Middleware/CP/Localize.php(0): call_user_func_array
#55 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#54 core/Http/Middleware/CP/DefaultLocale.php(28): handle
#53 core/Http/Middleware/CP/DefaultLocale.php(0): call_user_func_array
#52 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#51 core/Http/Middleware/CpEnabled.php(23): handle
#50 core/Http/Middleware/CpEnabled.php(0): call_user_func_array
#49 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#48 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(0): call_user_func
#47 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#46 vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): runRouteWithinStack
#45 vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): dispatchToRoute
#44 vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): dispatch
#43 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Foundation\Http\{closure}
#42 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(0): call_user_func
#41 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): Illuminate\Pipeline\{closure}
#40 /var/www/foo/releases/20180314141355/site/addons/RequestId/RequestIdMiddleware.php(14): handle
#39 /var/www/foo/releases/20180314141355/site/addons/RequestId/RequestIdMiddleware.php(0): call_user_func_array
#38 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#37 /var/www/foo/releases/20180314141355/site/addons/HtmlMinify/HtmlMinifyMiddleware.php(12): handle
#36 /var/www/foo/releases/20180314141355/site/addons/HtmlMinify/HtmlMinifyMiddleware.php(0): call_user_func_array
#35 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#34 /var/www/foo/releases/20180314141355/site/addons/ControlPanel/ControlPanelMiddleware.php(14): handle
#33 /var/www/foo/releases/20180314141355/site/addons/ControlPanel/ControlPanelMiddleware.php(0): call_user_func_array
#32 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#31 /var/www/foo/releases/20180314141355/site/addons/Customer/CustomerMiddleware.php(35): handle
#30 /var/www/foo/releases/20180314141355/site/addons/Customer/CustomerMiddleware.php(0): call_user_func_array
#29 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#28 core/Http/Middleware/PersistStache.php(22): handle
#27 core/Http/Middleware/PersistStache.php(0): call_user_func_array
#26 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#25 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): handle
#24 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(0): call_user_func_array
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#22 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): handle
#21 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(0): call_user_func_array
#20 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#19 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): handle
#18 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(0): call_user_func_array
#17 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#16 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): handle
#15 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(0): call_user_func_array
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#13 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): handle
#12 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(0): call_user_func_array
#11 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#10 core/StaticCaching/Middleware/Retrieve.php(33): handle
#9 core/StaticCaching/Middleware/Retrieve.php(0): call_user_func_array
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#7 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): handle
#6 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(0): call_user_func_array
#5 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): Illuminate\Pipeline\{closure}
#4 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(0): call_user_func
#3 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): sendRequestThroughRouter
#1 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): handle
#0 /var/www/foo/releases/20180314141355/index.php(155): null
```

### Actual behaviour
Search request threw an exception.

### Steps to reproduce
1. Unknown 

### Server Details

**Operating System**: CentOS 7

**Web Server:** nginx

**PHP Version:** 7.2

**Statamic Version:** 2.8.7

**Updated from an older Statamic or fresh install:** Updated

**List of installed addons:** Mostly custom

**Comment by jackmcdade** [comment]
Does this happen every time? Did you run the search indexer?
