### ISSUE TITLE
CollectionTags error after upgrade from 2.8.10 to 2.8.12

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#1912]
I upgraded one of my sites from 2.8.10 to 2.8.12 and now I am getting the following error when limiting collection results with taxonomies.

This is the offending code:

```
{{ collection:posts limit="1" taxonomy:post_type="news" :taxonomy:post_category="{ if !post_category }{ segment_1 }{ else }post_category{ /if }" scope="specific_posts" }}
```

This is the exact part of the code that is causing the error below
```
:taxonomy:post_category="{ if !post_category }{ segment_1 }{ else }post_category{ /if }"
```

```[2018-05-05 01:09:06] local.ERROR: ErrorException: array_filter() expects parameter 1 to be array, null given in /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php:214
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_filter() ...', '/home/vagrant/g...', 214, Array)
#1 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(214): array_filter(NULL)
#2 [internal function]: Statamic\Addons\Collection\CollectionTags->Statamic\Addons\Collection\{closure}(NULL, 'taxonomy:post_c...')
#3 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(469): array_map(Object(Closure), Array, Array)
#4 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(217): Illuminate\Support\Collection->map(Object(Closure))
#5 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(154): Statamic\Addons\Collection\CollectionTags->getTaxonomyCollectionFromParams('posts')
#6 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(124): Statamic\Addons\Collection\CollectionTags->getTaxonomyCollection('posts')
#7 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(94): Statamic\Addons\Collection\CollectionTags->getCollection('posts')
#8 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Collection/CollectionTags.php(82): Statamic\Addons\Collection\CollectionTags->collect('posts')
#9 [internal function]: Statamic\Addons\Collection\CollectionTags->__call('posts', Array)
#10 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Engine.php(163): call_user_func(Array)
#11 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n\n\t\t\t\t\t\t{{ if n...', Array)
#12 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Parser.php(513): call_user_func_array(Array, Array)
#13 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Parser.php(113): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="w-f...', Array, Array)
#14 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('<div class="w-f...', Array, Array, false)
#15 /home/vagrant/gitlab/customers/domain/public/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<div class="w-f...', Array, Array)
#16 /home/vagrant/gitlab/customers/domain/public/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('<div class="w-f...', Array)
#17 [internal function]: Statamic\Addons\Partial\PartialTags->__call('sitePageSidebar', Array)
#18 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Engine.php(163): call_user_func(Array)
#19 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial', Array, '', Array)
#20 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Parser.php(513): call_user_func_array(Array, Array)
#21 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Parser.php(113): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="con...', Array, Array)
#22 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('{{ partial:site...', Array, Array, false)
#23 /home/vagrant/gitlab/customers/domain/public/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{ partial:site...', Array, Array)
#24 /home/vagrant/gitlab/customers/domain/public/statamic/core/View/Antlers/Engine.php(70): Statamic\API\Parse::template('{{ partial:site...', Array)
#25 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/home/vagrant/g...', Array)
#26 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#27 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#28 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#29 /home/vagrant/gitlab/customers/domain/public/statamic/core/Http/Controllers/StatamicController.php(253): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#30 [internal function]: Statamic\Http\Controllers\StatamicController->index('news-and-articl...')
#31 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#32 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#33 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#34 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#38 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#40 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#41 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#42 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#45 /home/vagrant/gitlab/customers/domain/public/statamic/core/StaticCaching/Middleware/Cache.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Statamic\StaticCaching\Middleware\Cache->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#50 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#52 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#53 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#56 /home/vagrant/gitlab/customers/domain/public/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /home/vagrant/gitlab/customers/domain/public/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#82 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#83 /home/vagrant/gitlab/customers/domain/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#84 /home/vagrant/gitlab/customers/domain/public/index.php(142): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#85 {main}    
```

**Comment by jasonvarga** [comment]
All that templating inside the parameter should have never worked. I'm surprised it ever did.

**Comment by thestepafter** [comment]
The templating still works, the issue is with `:` before the `taxonomy` tag.

**Comment by jasonvarga** [comment]
The `:` parses the parameter.

```
---
foo: bar
---
param="foo"  <-- this would be "foo"
:param="foo"  <-- this would be "bar"
```

**Comment by thestepafter** [comment]
Ok, makes sense. The issue is that in 2.8.12 using `:` doesn't work but in 2.8.10 it does. The templating inside the tag works in 2.8.12 when you remove the `:`.

**Comment by jasonvarga** [comment]
Right, 2.8.12 fixed a bug that you were relying on.

```
:param="non_existent_var"
```

This fell back to the string "non_existent_var" in 2.8.11.
In 2.8.12 it's `null`
