### ISSUE TITLE
[Bug] Can't access globals inside email template

### ISSUE THREAD

**Issue by jimblue** [statamic/v2-hub#2224]
**Describe the bug**
When using globals inside a custom email template it return an empty string

**Environment details (please complete the following information):**
 - Statamic Version 2.10.7
 - Upgrade
 -  macOS 10.14
 - Valet
 - PHP Version 7.2.11
 - Addons installed: Charge, Fetch, Google Analytics, Instagram, Power Tools, Seo pro, Webpacker

**Comment by jackmcdade** [comment]
What's the source of your emails? Forms, presumably? Does Charge send emails?

**Comment by jackmcdade** [comment]
Also, technically this isn't a bug. We don't provide globals because all injected data will be sent w/ "Automagic" emails, where the view `$data` is dumped into the email template. There would be a lot of extra data in there in that case. Need to know a bit more about what you want to do so we can look for a good middle ground.

**Comment by edalzell** [comment]
Charge does send emails

**Comment by jimblue** [comment]
The source is a contact form. (create with Statamic tag `{{ form:create }}`)
The email template is a simple html email.
I'm trying to access global where I have an author entry. (name, professions, email...)
I use this global entries for email signature. Thanks and let me know if you need more infos.

**Comment by jorenvanhee** [comment]
I found a workaround. You can add a custom tag via [site helpers](https://docs.statamic.com/addons/site-helpers).

This is the helper I've written:

```php
public function global()
{
    $key = $this->getParam('key');
    [$set, $name] = explode(':', $key);

    $globalSet = GlobalSet::whereHandle($set);
    $globalSet->locale(app()->getLocale());

    return $globalSet->get($name) ?: $key;
}
```

You can use it like this:

```
{{ site:global key="contact_form:confirmation_email_title" }}
```

It's not ideal, and probably does not work for everything. I only used it with basic text field types. Also, it doesn't fallback to the default language if there's no translation. You can probably fix this, but I didn't want to spend too much time on it.

**Comment by aerni90** [comment]
To me this is a very important feature request for multilingual websites. It would be even better, if we could manage email content from within the forms settings, so we don't have to create a global for it.

**Comment by aerni90** [comment]
@jorenvanhee I tried your workaround and added the site helper to the `Tags.php` and the tag `{{ site:global key="email_template:text" }}` to my email template. But I can't seem to make it work, as I get the following error upon sending the form. Can you help me out here?
```
[2019-02-21 11:22:01] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Class 'Statamic\SiteHelpers\GlobalSet' not found in /Users/michael/Valet/baerenmatte/site/helpers/Tags.php:29
Stack trace:
#0 [internal function]: Statamic\SiteHelpers\Tags->global()
#1 /Users/michael/Valet/baerenmatte/statamic/core/View/Antlers/Engine.php(163): call_user_func(Array)
#2 [internal function]: Statamic\View\Antlers\Engine::renderTag('site', Array, '', Array)
#3 /Users/michael/Valet/baerenmatte/statamic/core/View/Antlers/Parser.php(513): call_user_func_array(Array, Array)
#4 /Users/michael/Valet/baerenmatte/statamic/core/View/Antlers/Parser.php(113): Statamic\View\Antlers\Parser->parseCallbackTags('Hallo Jonas Wip...', Array, Array)
#5 /Users/michael/Valet/baerenmatte/statamic/core/View/Antlers/Template.php(32): Statamic\View\Antlers\Parser->parse('Hallo Jonas Wip...', Array, Array, false)
#6 /Users/michael/Valet/baerenmatte/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('Hallo {{ first_...', Array, Array)
#7 /Users/michael/Valet/baerenmatte/statamic/core/Email/Sender.php(114): Statamic\API\Parse::template('Hallo {{ first_...', Array)
#8 /Users/michael/Valet/baerenmatte/statamic/core/Email/Sender.php(44): Statamic\Email\Sender->parseEmailTemplate()
#9 /Users/michael/Valet/baerenmatte/statamic/core/Email/Message.php(232): Statamic\Email\Sender->send(Object(Statamic\Email\Message))
#10 /Users/michael/Valet/baerenmatte/statamic/core/Email/Builder.php(136): Statamic\Email\Message->send()
#11 /Users/michael/Valet/baerenmatte/statamic/bundles/Form/FormListener.php(193): Statamic\Email\Builder->send()
#12 /Users/michael/Valet/baerenmatte/statamic/bundles/Form/FormListener.php(146): Statamic\Addons\Form\FormListener->sendEmail(Object(Statamic\Forms\Submission), Array)
#13 [internal function]: Statamic\Addons\Form\FormListener->sendEmails(Object(Statamic\Forms\Submission))
#14 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#15 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('Form.submission...', Array, false)
#16 /Users/michael/Valet/baerenmatte/statamic/core/Extend/Extensible.php(215): event('Form.submission...', Object(Statamic\Forms\Submission))
#17 /Users/michael/Valet/baerenmatte/statamic/bundles/Form/FormListener.php(74): Statamic\Extend\Listener->emitEvent('submission.crea...', Object(Statamic\Forms\Submission))
#18 [internal function]: Statamic\Addons\Form\FormListener->create(NULL)
#19 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#20 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('Form.create', Array, false)
#21 /Users/michael/Valet/baerenmatte/statamic/core/API/Event.php(16): event('Form.create', NULL)
#22 /Users/michael/Valet/baerenmatte/statamic/core/Http/Controllers/StatamicController.php(143): Statamic\API\Event::fire('Form.create', NULL)
#23 /Users/michael/Valet/baerenmatte/statamic/core/Http/Controllers/StatamicController.php(97): Statamic\Http\Controllers\StatamicController->fireEvent('Form', 'create', NULL)
#24 [internal function]: Statamic\Http\Controllers\StatamicController->controllerTrigger('Form', 'create')
#25 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#26 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('controllerTrigg...', Array)
#27 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'controllerTrigg...')
#28 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#33 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(68): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'controllerTrigg...')
#34 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'controllerTrigg...')
#35 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#36 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(674): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 /Users/michael/Valet/baerenmatte/site/addons/SeoPro/Middleware/GenerateReport.php(13): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Statamic\Addons\SeoPro\Middleware\GenerateReport->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /Users/michael/Valet/baerenmatte/site/addons/MinifyHTML/MinifyHTMLMiddleware.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Statamic\Addons\MinifyHTML\MinifyHTMLMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /Users/michael/Valet/baerenmatte/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(51): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /Users/michael/Valet/baerenmatte/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /Users/michael/Valet/baerenmatte/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#82 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#83 /Users/michael/Valet/baerenmatte/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#84 /Users/michael/Valet/baerenmatte/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#85 /Users/michael/.composer/vendor/laravel/valet/server.php(151): require('/Users/michael/...')
#86 {main}  
```

**Comment by jorenvanhee** [comment]
Try adding this `use Statamic\API\GlobalSet;` at the top of your Tags file. Under the other imports.

**Comment by aerni90** [comment]
That worked. Thank you so much!

**Comment by robdekort** [comment]
I made a custom e-mail template with a footer containing several customer related stuff like e-mail, link to privacy policy, their address and their phone number. I figured I could request globals and variables in the mail template.
