### ISSUE TITLE
Error when trying to save caching settings

### ISSUE THREAD

**Issue by wratke** [statamic/v2-hub#2318]
After updating to the most recent version of Statamic, I'm getting the following error when I try to save  changes to the Settings>Caching page:

```
[2019-01-03 16:15:22] production.ERROR: exception 'ErrorException' with message 'array_key_exists(): The first argument should be either a string or an integer' in /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php:694
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'array_key_exist...', '/home/ninesixte...', 694, Array)
#1 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(694): array_key_exists(false, Array)
#2 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(204): Symfony\Component\Yaml\Parser->parseValue('*', 0, 'sequence')
#3 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(483): Symfony\Component\Yaml\Parser->doParse('- *', 0)
#4 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(332): Symfony\Component\Yaml\Parser->parseBlock(22, '- *', 0)
#5 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(483): Symfony\Component\Yaml\Parser->doParse('urls:\n  - *', 0)
#6 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(332): Symfony\Component\Yaml\Parser->parseBlock(21, 'urls:\n  - *', 0)
#7 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(483): Symfony\Component\Yaml\Parser->doParse('project_grid_se...', 0)
#8 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(332): Symfony\Component\Yaml\Parser->parseBlock(5, 'project_grid_se...', 0)
#9 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(483): Symfony\Component\Yaml\Parser->doParse('collections:\n  ...', 0)
#10 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(332): Symfony\Component\Yaml\Parser->parseBlock(4, 'collections:\n  ...', 0)
#11 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Parser.php(105): Symfony\Component\Yaml\Parser->doParse('stache_always_u...', 0)
#12 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/symfony/yaml/Yaml.php(82): Symfony\Component\Yaml\Parser->parse('stache_always_u...', 0)
#13 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/API/YAML.php(50): Symfony\Component\Yaml\Yaml::parse('stache_always_u...')
#14 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/API/YAML.php(39): Statamic\API\YAML::parseSymfony('stache_always_u...')
#15 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/API/YAML.php(33): Statamic\API\YAML::parseYaml('stache_always_u...')
#16 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Controllers/SettingsController.php(62): Statamic\API\YAML::parse('stache_always_u...')
#17 [internal function]: Statamic\Http\Controllers\SettingsController->update('caching')
#18 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#19 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('update', Array)
#20 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\SettingsController), Object(Illuminate\Routing\Route), 'update')
#21 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\SettingsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'update')
#27 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'update')
#28 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#29 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/Configurable.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Statamic\Http\Middleware\CP\Configurable->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/Outpost.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/Localize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/AddHeaders.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Statamic\Http\Middleware\CP\AddHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CpEnabled.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Statamic\Http\Middleware\CpEnabled->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#57 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#58 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#60 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /home/ninesixteen/beta.ninesixteen.ca/site/addons/MinifyHTML/MinifyHTMLMiddleware.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Statamic\Addons\MinifyHTML\MinifyHTMLMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#70 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#73 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#76 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#79 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#81 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#82 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#83 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#84 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#85 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#86 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#87 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#88 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#89 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#90 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#91 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#92 /home/ninesixteen/beta.ninesixteen.ca/index.php(156): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#93 {main}  
```

**Comment by wratke** [comment]
I no longer have this error after upgrading PHP to 7.2.
