### ISSUE TITLE
Error when trying to search a collection

### ISSUE THREAD

**Issue by wratke** [statamic/v2-hub#2319]
I'm getting the following error in the logs when I try to use the search function in the control panel in the most recent version of Statamic. I checked to make sure the mbstring extension is installed to the server and it seems to be enabled.

```
[2019-01-01 16:30:19] production.ERROR: exception 'ErrorException' with message 'mb_ereg_replace(): mbregex compile err: invalid code point value' in /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Search/Comb/Comb.php:377
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'mb_ereg_replace...', '/home/ninesixte...', 377, Array)
#1 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Search/Comb/Comb.php(377): mb_ereg_replace('[^\\w\\d\\-\\.:+\\s&...', '', 'test')
#2 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Search/Comb/Comb.php(246): Statamic\Search\Comb\Comb->preformat('test')
#3 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Search/Comb/Index.php(82): Statamic\Search\Comb\Comb->lookUp('test')
#4 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Search/Search.php(33): Statamic\Search\Comb\Index->search('test', NULL)
#5 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/API/Search.php(28): Statamic\Search\Search->search('test', NULL)
#6 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Controllers/EntriesSearchController.php(45): Statamic\API\Search::get('test')
#7 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Controllers/EntriesSearchController.php(21): Statamic\Http\Controllers\EntriesSearchController->searchDefaultIndex('grid_section', 'test')
#8 [internal function]: Statamic\Http\Controllers\EntriesSearchController->search(Object(Illuminate\Http\Request), 'grid_section')
#9 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#10 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('search', Array)
#11 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\EntriesSearchController), Object(Illuminate\Routing\Route), 'search')
#12 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#13 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#17 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\EntriesSearchController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'search')
#18 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'search')
#19 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#20 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#21 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#26 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/Outpost.php(48): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#29 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/Localize.php(25): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Statamic\Http\Middleware\CP\Localize->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#32 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CP/AddHeaders.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Statamic\Http\Middleware\CP\AddHeaders->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/CpEnabled.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Statamic\Http\Middleware\CpEnabled->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#44 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#45 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#49 /home/ninesixteen/beta.ninesixteen.ca/site/addons/MinifyHTML/MinifyHTMLMiddleware.php(20): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Statamic\Addons\MinifyHTML\MinifyHTMLMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/Http/Middleware/TransformsRequest.php(31): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Statamic\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#70 /home/ninesixteen/beta.ninesixteen.ca/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#73 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#76 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#78 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#79 /home/ninesixteen/beta.ninesixteen.ca/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#80 /home/ninesixteen/beta.ninesixteen.ca/index.php(156): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#81 {main}  
```

**Comment by jackmcdade** [comment]
What version of PHP are you running?

**Comment by wratke** [comment]
The server was using 5.4, this works after upgrading PHP to 7.2.
