### ISSUE TITLE
S3 Assets field showing ErrorException when it is null 

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#528]
### Steps to reproduce
1. Enable s3 assets
2. Edit a page with assets field

### Expected behaviour
Assets field without anything chosen should display the standard asset upload button/box

### Actual behaviour
When asset field is empty, it's showing endless loading animation

### Server configuration
**Operating system**: OS X El Capitan [latest]

**Web server:** MAMP Pro [latest]

**PHP version:** 5.6.10

**Statamic version:** V2 B19

**Updated from an older Statamic or fresh install:** Fresh

**List of installed addons:** none

#### Web server error log
```
Insert your webserver log here
```

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-03-09 14:29:25] dev.ERROR: exception 'ErrorException' with message 'explode() expects parameter 2 to be string, array given' in /Users/rudy/Sites/thelundingroup/statamic/core/Stache/File/LocalizedAssetCache.php:127
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'explode() expec...', '/Users/rudy/Sit...', 127, Array)
#1 /Users/rudy/Sites/thelundingroup/statamic/core/Stache/File/LocalizedAssetCache.php(127): explode('/', Array, 2)
#2 /Users/rudy/Sites/thelundingroup/statamic/core/Stache/File/AssetCacheService.php(62): Statamic\Stache\File\LocalizedAssetCache->getAsset(NULL)
#3 /Users/rudy/Sites/thelundingroup/statamic/core/Assets/File/AssetService.php(32): Statamic\Stache\File\AssetCacheService->get(NULL, NULL)
#4 /Users/rudy/Sites/thelundingroup/statamic/core/API/Asset.php(43): Statamic\Assets\File\AssetService->getUuid(NULL, NULL)
#5 /Users/rudy/Sites/thelundingroup/statamic/core/Http/Controllers/AssetsController.php(91): Statamic\API\Asset::uuidRaw(NULL)
#6 [internal function]: Statamic\Http\Controllers\AssetsController->get()
#7 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#8 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('get', Array)
#9 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), 'get')
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\AssetsController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'get')
#16 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'get')
#17 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /Users/rudy/Sites/thelundingroup/statamic/core/Http/Middleware/VersionCheck.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Statamic\Http\Middleware\VersionCheck->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 /Users/rudy/Sites/thelundingroup/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#30 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#31 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#32 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#34 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /Users/rudy/Sites/thelundingroup/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /Users/rudy/Sites/thelundingroup/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /Users/rudy/Sites/thelundingroup/public/index.php(128): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main}  
```

#### Browser log
![screen shot 2016-03-09 at 10 30 06 am](https://cloud.githubusercontent.com/assets/1151181/13638496/e81db94a-e5e2-11e5-9e6a-68e010e1c29c.png)

**Comment by jasonvarga** [comment]
I believe this is fixed. Reopen after the next release lands if you need to.

**Comment by lesaff** [comment]
Alright, thx
