### ISSUE TITLE
404 On Admin Page

### ISSUE THREAD

**Issue by garethredfern** [statamic/v2-hub#640]
### Steps to reproduce
1. Clear everything using the please command.
2. Create theme with the please command.
3. Create user with the please command (super admin).
4. go to /cp/users and click on username

### Expected behaviour
Go to user edit screen.

### Actual behaviour
404 returned link it takes you to is /index.php/cp/users/garethredfern

### Server configuration
Clean install on MAMP Pro

### Logs
[2016-04-28 08:38:34] production.ERROR: exception 'Statamic\Exceptions\FileNotFoundException' with message 'Fieldset(s) not found: [user]' in /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/API/Fieldset.php:55
Stack trace:
#0 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Data/Users/File/User.php(318): Statamic\API\Fieldset::get('user')
#1 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Controllers/UsersController.php(162): Statamic\Data\Users\File\User->fieldset()
#2 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Controllers/UsersController.php(108): Statamic\Http\Controllers\UsersController->populateWithBlanks(Object(Statamic\Data\Users\File\User))
#3 [internal function]: Statamic\Http\Controllers\UsersController->edit('garethredfern')
#4 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#5 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('edit', Array)
#6 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), 'edit')
#7 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#8 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#10 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\UsersController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'edit')
#13 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'edit')
#14 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#15 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#17 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#21 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#24 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#25 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#26 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#27 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#28 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#32 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#55 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#56 /Applications/MAMP/htdocs/clients/jc3dp-statamic/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#57 /Applications/MAMP/htdocs/clients/jc3dp-statamic/index.php(157): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#58 {main}

**Comment by garethredfern** [comment]
Closing for now, not come across it again.
