### ISSUE TITLE
Hundreds of app_key regenerated when there's no app_key value in the system.yaml

### ISSUE THREAD

**Issue by lesaff** [statamic/v2-hub#692]
### Steps to reproduce
1. Edit/Open `site/settings/system.yaml`
2. Delete the `app_key:` value
3. Reload CP
### Expected behaviour

New `app_key` to be generated by CP
### Actual behaviour

CP reloaded and generates over a hundred of new `app_keys` until browser throws a `redirected too many times` error
### Server configuration

**Operating system**: Latest El Capitan

**Web server:** Valet 1.1.11

**PHP version:** 7

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** Update from 2.0.2
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
[2016-05-18 19:33:09] dev.ERROR: RuntimeException: No supported encrypter found. The cipher and / or key length are invalid. in /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php:29
Stack trace:
#0 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(738): Illuminate\Encryption\EncryptionServiceProvider->Illuminate\Encryption\{closure}(Object(Statamic\Application), Array)
#1 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build(Object(Closure), Array)
#2 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('encrypter', Array)
#3 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\Foundation\Application->make('encrypter')
#4 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#5 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(774): Illuminate\Container\Container->getDependencies(Array, Array)
#6 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Illuminate\\Cook...', Array)
#7 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\\Cook...', Array)
#8 /Users/rudy/Sites/alsetenergy/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\Foundation\Application->make('Illuminate\\Cook...')
#9 /Users/rudy/Sites/alsetenergy/public/index.php(132): Illuminate\Foundation\Http\Kernel->terminate(Object(Illuminate\Http\Request), Object(Illuminate\Http\RedirectResponse))
#10 /Users/rudy/.composer/vendor/laravel/valet/server.php(106): require('/Users/rudy/Sit...')
#11 {main}  
```
#### Browser log

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

![screen shot 2016-05-18 at 4 25 03 pm](https://cloud.githubusercontent.com/assets/1151181/15372583/7f3b7ce8-1d17-11e6-8160-483c318172a7.png)

**Comment by johnmeilleur** [comment]
I can reproduce this behaviour as well.

**Comment by lesaff** [comment]
v2 is running above root, if that helps
