### ISSUE TITLE
OldTags in conditional throw error when used "correctly"

### ISSUE THREAD

**Issue by curtisblackwell** [statamic/v2-hub#700]
### Steps to reproduce
1. Write a conditional with single-curlies wrapped around the `old` tag `{{ if {old:location} === title }}`
### Expected behaviour

The page should render without error.
### Actual behaviour

The parser assaults me viciously.
### Server configuration

**Operating system**: OS X

**Web server:** Valet

**PHP version:** 7.0.6

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** Updated
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
[2016-05-20 00:27:10] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Parse error: syntax error, unexpected '===' (T_IS_IDENTICAL) in /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(1335) : eval()'d code:2
Stack trace:
#0 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(892): Statamic\View\Antlers\Parser->parsePhp('\n          <opt...')
#1 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(131): Statamic\View\Antlers\Parser->parseConditionals('\n          <opt...', Array, Array)
#2 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n          <opt...', Array, Array, false)
#3 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(66): Statamic\View\Antlers\Template::parse('\n          <opt...', Array, Array)
#4 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/API/Parse.php(36): Statamic\View\Antlers\Template::parseLoop('\n          <opt...', Array, true, Array)
#5 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Extend/Tags.php(220): Statamic\API\Parse::templateLoop('\n          <opt...', Array, true, Array)
#6 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Collection/CollectionTags.php(130): Statamic\Extend\Tags->parseLoop(Object(Statamic\Data\Entries\EntryCollection))
#7 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Collection/CollectionTags.php(90): Statamic\Addons\Collection\CollectionTags->output()
#8 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Collection/CollectionTags.php(66): Statamic\Addons\Collection\CollectionTags->collect('locations')
#9 [internal function]: Statamic\Addons\Collection\CollectionTags->__call('locations', Array)
#10 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'locations')
#11 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n          <opt...', Array)
#12 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#13 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('    <div class=...', Array, Array)
#14 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('    <div class=...', Array, Array, false)
#15 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('\n    <div class...', Array, Array)
#16 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Extend/Tags.php(201): Statamic\API\Parse::template('\n    <div class...', Array, Array)
#17 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Form/FormTags.php(70): Statamic\Extend\Tags->parse(Array)
#18 [internal function]: Statamic\Addons\Form\FormTags->create('create')
#19 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'create')
#20 [internal function]: Statamic\View\Antlers\Engine::renderTag('form', Array, '\n    <div class...', Array)
#21 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#22 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('\n  \n  {{ form:c...', Array, Array)
#23 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n  \n  {{ form:c...', Array, Array, false)
#24 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('\n{{ if {form:er...', Array, Array)
#25 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Extend/Tags.php(201): Statamic\API\Parse::template('\n{{ if {form:er...', Array, Array)
#26 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Form/FormTags.php(29): Statamic\Extend\Tags->parse(Array)
#27 [internal function]: Statamic\Addons\Form\FormTags->set('set')
#28 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'set')
#29 [internal function]: Statamic\View\Antlers\Engine::renderTag('form', Array, '\n{{ if {form:er...', Array)
#30 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#31 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('{{ form:set is=...', Array, Array)
#32 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('{{ form:set is=...', Array, Array, false)
#33 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{ form:set is=...', Array, Array)
#34 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('{{ form:set is=...', Array)
#35 [internal function]: Statamic\Addons\Partial\PartialTags->__call('index', Array)
#36 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#37 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial', Array, '', Array)
#38 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#39 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="her...', Array, Array)
#40 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('<div class="her...', Array, Array, false)
#41 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<div class="her...', Array, Array)
#42 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/View/Antlers/Engine.php(69): Statamic\API\Parse::template('<div class="her...', Array)
#43 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/Users/curtisbl...', Array)
#44 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#45 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#46 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#47 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/symfony/http-foundation/Response.php(200): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#48 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#49 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(598): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#50 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Http/Controllers/StatamicController.php(163): response(Object(Illuminate\View\View))
#51 [internal function]: Statamic\Http\Controllers\StatamicController->index('locations/oak-c...')
#52 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#53 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#54 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#55 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#56 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#61 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#62 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#63 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#65 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#68 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#69 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#70 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#71 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#73 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#74 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#85 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#86 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#87 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#88 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#89 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Http/Middleware/CP/DefaultLocale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#90 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#91 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#92 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#93 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#94 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#95 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#96 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#97 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#98 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#99 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#100 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#101 /Users/curtisblackwell/Sites/thecommondesk/html/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#102 /Users/curtisblackwell/Sites/thecommondesk/html/index.php(127): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#103 /Users/curtisblackwell/.composer/vendor/laravel/valet/server.php(106): require('/Users/curtisbl...')
#104 {main}  
```

**Comment by jasonvarga** [comment]
Can't recreate. Works fine here.

**Comment by jasonvarga** [comment]
We changed something regarding `old` tags in 2.0.6 - not sure it's quite related to this though. Let me know if you still run into this issue.

**Comment by curtisblackwell** [comment]
I'll take a look after we update Statamic on this site. We're having trouble with the CP when we update (probably something I need to update in my Valet driver), and we need to get the templates built out soon, so it'll probably be a while.

**Comment by jackmcdade** [comment]
I'm 99% sure 2.0.7 is the fix fot that.

**Comment by curtisblackwell** [comment]
The CP issue? Were other people having that issue, too? Didn't see any mention of it, so I assumed it was b/c of my custom driver.

**Comment by warkior** [comment]
I still seem to be having the issue on a simple sample form I created for testing the process. v.2.0.7.
I have a simple country selection field, which is populated by an addon tag like so...
```php
public function countriesSelectOptions()
    {
        $countries = [
            [
                'shortcode' => 'CA',
                'description' => 'Canada'
            ],
            [
                'shortcode' => 'US',
                'description' => 'United States'
            ],
            [
                'shortcode' => 'IN',
                'description' => 'Indonesia'
            ],
        ];
        $countries = $this->parseLoop($countries);

        return $countries;
    }
```

Then, in my template I have this...
```html
<select name="country" id="country" required="">
	<option>Select country</option>
	{{ myaddon:countries_select_options }}
	<option value="{{ shortcode }}" {{ if {old:country} == shortcode }} selected=selected {{ /if }}>{{ description }}</option>
	{{ /myaddon:countries_select_options }}
</select>
```
The result is an ugly Laravel error:
```
ParsingException in Parser.php line 1339: You have a syntax error in your Lex tags. The offending code:
<option value="{{ shortcode }}" if ( == 'CA'): selected=selected endif; >{{ description }}</option>
```

**Comment by warkior** [comment]
Some additional info... it only shows that parse error if I have NOT submitted any data. ie, on a new display of the form.

**Comment by curtisblackwell** [comment]
I figured out the aforementioned Valet issue… was a sloppy mistake I made when I rushed through customizing the driver.

**Comment by jasonvarga** [comment]
Old tags are variables since 2.6.4. You should be able to `old:foo` instead of `{old:foo}` and have a much easier time.
