### ISSUE TITLE
fit="crop_focal" causes fatal error in LocalizedAssetCache

### ISSUE THREAD

**Issue by andypillip** [statamic/v2-hub#719]
### Steps to reproduce
1. Create a page with an assigned image asset
2. Create a template for that page that contains the `glide` tag with `width`, `height` and `fit="crop_focal"`
3. Call the page in frontend

### Expected behaviour
Page displays with the image cropped to the correct dimensions.

### Actual behaviour
Error message:

> ErrorException in LocalizedAssetCache.php line 127:
> explode() expects parameter 2 to be string, array given

### Server configuration
**Operating system**: Fedora 23

**Web server:** php -S localhost:3000

**PHP version:** 5.6.20

**Statamic version:** 2.0.5

**Updated from an older Statamic or fresh install:** Update, but asset configuration, fieldset and template are corrected already.

**List of installed addons:** none

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-05-30 15:02:35] dev.ERROR: exception 'ErrorException' with message 'explode() expects parameter 2 to be string, array given' in /home/andy/…/statamic/core/Stache/File/LocalizedAssetCache.php:127
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'explode() expec...', '/home/andy/Arbe...', 127, Array)
#1 /home/andy/…/statamic/core/Stache/File/LocalizedAssetCache.php(127): explode('/', Array, 2)
#2 /home/andy/…/statamic/core/Stache/File/AssetCacheService.php(62): Statamic\Stache\File\LocalizedAssetCache->getAsset(NULL)
#3 /home/andy/…/statamic/core/Assets/File/AssetService.php(32): Statamic\Stache\File\AssetCacheService->get(NULL, NULL)
#4 /home/andy/…/statamic/core/API/Asset.php(43): Statamic\Assets\File\AssetService->getUuid(NULL, NULL)
#5 /home/andy/…/statamic/core/Assets/Manipulation/Image/GlideUrlBuilder.php(178): Statamic\API\Asset::uuidRaw(NULL)
#6 /home/andy/…/statamic/bundles/Glide/GlideTags.php(61): Statamic\Assets\Manipulation\Image\GlideUrlBuilder->fit('crop_focal')
#7 /home/andy/…/statamic/bundles/Glide/GlideTags.php(27): Statamic\Addons\Glide\GlideTags->glide('/assets/img/201...')
#8 [internal function]: Statamic\Addons\Glide\GlideTags->__call('image', Array)
#9 [internal function]: Statamic\Addons\Glide\GlideTags->image('image')
#10 /home/andy/…/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'image')
#11 [internal function]: Statamic\View\Antlers\Engine::renderTag('glide:image', Array, '', Array)
#12 /home/andy/…/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#13 /home/andy/…/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<img alt="" cla...', Array, Array)
#14 /home/andy/…/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('{{# expecting: ...', Array, Array, false)
#15 /home/andy/…/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{# expecting: ...', Array, Array)
#16 /home/andy/…/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('{{# expecting: ...', Array)
#17 [internal function]: Statamic\Addons\Partial\PartialTags->__call('lazyImage', Array)
#18 [internal function]: Statamic\Addons\Partial\PartialTags->lazyImage('lazy-image')
#19 /home/andy/…/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'lazy-image')
#20 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial:lazy-im...', Array, '', Array)
#21 /home/andy/…/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#22 /home/andy/…/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('      {{ partia...', Array, Array)
#23 /home/andy/…/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n      {{ parti...', Array, Array, false)
#24 /home/andy/…/statamic/core/View/Antlers/Template.php(66): Statamic\View\Antlers\Template::parse('\n      {{ parti...', Array, Array)
#25 /home/andy/…/statamic/core/API/Parse.php(36): Statamic\View\Antlers\Template::parseLoop('\n      {{ parti...', Array, true, Array)
#26 /home/andy/…/statamic/core/Extend/Tags.php(220): Statamic\API\Parse::templateLoop('\n      {{ parti...', Array, true, Array)
#27 /home/andy/…/statamic/bundles/Assets/AssetsTags.php(100): Statamic\Extend\Tags->parseLoop(Object(Statamic\Assets\AssetCollection))
#28 /home/andy/…/statamic/bundles/Assets/AssetsTags.php(92): Statamic\Addons\Assets\AssetsTags->output()
#29 /home/andy/…/statamic/bundles/Asset/AssetTags.php(33): Statamic\Addons\Assets\AssetsTags->assets('4b680694-99e4-4...')
#30 [internal function]: Statamic\Addons\Asset\AssetTags->__call('teaserImageAbou...', Array)
#31 [internal function]: Statamic\Addons\Asset\AssetTags->teaserImageAbout('teaser_image_ab...')
#32 /home/andy/…/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'teaser_image_ab...')
#33 [internal function]: Statamic\View\Antlers\Engine::renderTag('asset:teaser_im...', Array, '\n      {{ parti...', Array)
#34 /home/andy/…/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#35 /home/andy/…/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('  <a href="/ueb...', Array, Array)
#36 /home/andy/…/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n  <a href="{{ ...', Array, Array, false)
#37 /home/andy/…/statamic/core/View/Antlers/Template.php(66): Statamic\View\Antlers\Template::parse('\n  <a href="{{ ...', Array, Array)
#38 /home/andy/…/statamic/core/API/Parse.php(36): Statamic\View\Antlers\Template::parseLoop('\n  <a href="{{ ...', Array, true, Array)
#39 /home/andy/…/statamic/core/Extend/Tags.php(220): Statamic\API\Parse::templateLoop('\n  <a href="{{ ...', Array, true, Array)
#40 /home/andy/…/statamic/bundles/Collection/CollectionTags.php(130): Statamic\Extend\Tags->parseLoop(Object(Statamic\Data\Content\ContentCollection))
#41 /home/andy/…/statamic/bundles/GetContent/GetContentTags.php(24): Statamic\Addons\Collection\CollectionTags->output()
#42 [internal function]: Statamic\Addons\GetContent\GetContentTags->index('index')
#43 /home/andy/…/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#44 [internal function]: Statamic\View\Antlers\Engine::renderTag('get_content', Array, '\n  <a href="{{ ...', Array)
#45 /home/andy/…/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#46 /home/andy/…/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="hom...', Array, Array)
#47 /home/andy/…/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('<div class="hom...', Array, Array, false)
#48 /home/andy/…/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<div class="hom...', Array, Array)
#49 /home/andy/…/statamic/core/View/Antlers/Engine.php(69): Statamic\API\Parse::template('<div class="hom...', Array)
#50 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/home/andy/Arbe...', Array)
#51 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#52 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#53 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#54 /home/andy/…/statamic/vendor/symfony/http-foundation/Response.php(200): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#55 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#56 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(598): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#57 /home/andy/…/statamic/core/Http/Controllers/StatamicController.php(163): response(Object(Illuminate\View\View))
#58 [internal function]: Statamic\Http\Controllers\StatamicController->index('/')
#59 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#60 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#61 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#62 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#66 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#67 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#68 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#69 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#70 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#71 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#73 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#75 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#76 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#77 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#78 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#79 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#80 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 /home/andy/…/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#83 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#84 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#85 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#86 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#87 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#88 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#89 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#90 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#91 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#92 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#93 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#94 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#95 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#96 /home/andy/…/statamic/core/Http/Middleware/CP/DefaultLocale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#97 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#98 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#99 /home/andy/…/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#100 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#101 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#102 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#103 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#104 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#105 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#106 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#107 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#108 /home/andy/…/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#109 /home/andy/…/index.php(156): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#110 /home/andy/…/statamic/server.php(21): require_once('/home/andy/Arbe...')
#111 {main}  

```

**Comment by jasonvarga** [comment]
I believe this is fixed for next release. I can't replicate it. Let me know if you still have this issue once you get your hands on it.
