### ISSUE TITLE
ErrorException in CollectionTags.php line 79: Array to string conversion

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#725]
### Steps to reproduce
1. Use a collections tag
2. Load page
3. Error appears (the collection has entries BTW)

### Expected behaviour
The page should load. And the collection tag should list the entries.

### Actual behaviour
I get this error.
```
in CollectionTags.php line 79
at HandleExceptions->handleError('8', 'Array to string conversion', '/Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php', '79', array('collection' => array('blog'))) in CollectionTags.php line 79
at CollectionTags->collect(array('blog')) in CollectionTags.php line 51
```
### Server configuration
MAMP PRO
PHP 5.6.10

**Statamic version:**
2.0.7

**Updated from an older Statamic or fresh install:**
Fresh

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-06-01 12:18:12] dev.ERROR: exception 'ErrorException' with message 'Array to string conversion' in /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php:79
Stack trace:
#0 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/Users/phil/Sit...', 79, Array)
#1 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php(51): Statamic\Addons\Collection\CollectionTags->collect(Array)
#2 [internal function]: Statamic\Addons\Collection\CollectionTags->index('index')
#3 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#4 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n      {{ posts...', Array)
#5 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#6 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="row...', Array, Array)
#7 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n<div class="ro...', Array, Array, false)
#8 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('\n<div class="ro...', Array, Array)
#9 /Users/phil/Sites/platinumlakemanagement/statamic/core/Extend/Tags.php(201): Statamic\API\Parse::template('\n<div class="ro...', Array, Array)
#10 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Cache/CacheTags.php(38): Statamic\Extend\Tags->parse(Array, Array)
#11 [internal function]: Statamic\Addons\Cache\CacheTags->index('index')
#12 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#13 [internal function]: Statamic\View\Antlers\Engine::renderTag('cache', Array, '\n<div class="ro...', Array)
#14 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#15 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('{{ cache }}\n<di...', Array, Array)
#16 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('{{ cache }}\n<di...', Array, Array, false)
#17 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{ cache }}\n<di...', Array, Array)
#18 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('{{ cache }}\n<di...', Array)
#19 [internal function]: Statamic\Addons\Partial\PartialTags->__call('layoutFooter', Array)
#20 [internal function]: Statamic\Addons\Partial\PartialTags->layoutFooter('layout_footer')
#21 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'layout_footer')
#22 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial:layout_...', Array, '', Array)
#23 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#24 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<!DOCTYPE html>...', Array, Array)
#25 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('<!DOCTYPE html>...', Array, Array, false)
#26 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<!DOCTYPE html>...', Array, Array)
#27 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(75): Statamic\API\Parse::template('<!DOCTYPE html>...', Array)
#28 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/Users/phil/Sit...', Array)
#29 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#30 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#31 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#32 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/symfony/http-foundation/Response.php(200): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#33 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#34 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(598): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#35 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Controllers/StatamicController.php(163): response(Object(Illuminate\View\View))
#36 [internal function]: Statamic\Http\Controllers\StatamicController->index('/')
#37 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#38 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#39 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#40 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#46 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#47 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#48 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#56 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#58 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CP/DefaultLocale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /Users/phil/Sites/platinumlakemanagement/index.php(128): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main}  
[2016-06-01 12:18:16] dev.ERROR: exception 'ErrorException' with message 'Array to string conversion' in /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php:79
Stack trace:
#0 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Array to string...', '/Users/phil/Sit...', 79, Array)
#1 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Collection/CollectionTags.php(51): Statamic\Addons\Collection\CollectionTags->collect(Array)
#2 [internal function]: Statamic\Addons\Collection\CollectionTags->index('index')
#3 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#4 [internal function]: Statamic\View\Antlers\Engine::renderTag('collection', Array, '\n      {{ posts...', Array)
#5 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#6 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<div class="row...', Array, Array)
#7 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('\n<div class="ro...', Array, Array, false)
#8 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('\n<div class="ro...', Array, Array)
#9 /Users/phil/Sites/platinumlakemanagement/statamic/core/Extend/Tags.php(201): Statamic\API\Parse::template('\n<div class="ro...', Array, Array)
#10 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Cache/CacheTags.php(38): Statamic\Extend\Tags->parse(Array, Array)
#11 [internal function]: Statamic\Addons\Cache\CacheTags->index('index')
#12 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'index')
#13 [internal function]: Statamic\View\Antlers\Engine::renderTag('cache', Array, '\n<div class="ro...', Array)
#14 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#15 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('{{ cache }}\n<di...', Array, Array)
#16 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('{{ cache }}\n<di...', Array, Array, false)
#17 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{ cache }}\n<di...', Array, Array)
#18 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Partial/PartialTags.php(30): Statamic\API\Parse::template('{{ cache }}\n<di...', Array)
#19 [internal function]: Statamic\Addons\Partial\PartialTags->__call('layoutFooter', Array)
#20 [internal function]: Statamic\Addons\Partial\PartialTags->layoutFooter('layout_footer')
#21 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'layout_footer')
#22 [internal function]: Statamic\View\Antlers\Engine::renderTag('partial:layout_...', Array, '', Array)
#23 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(527): call_user_func_array(Array, Array)
#24 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Parser.php(137): Statamic\View\Antlers\Parser->parseCallbackTags('<!DOCTYPE html>...', Array, Array)
#25 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('<!DOCTYPE html>...', Array, Array, false)
#26 /Users/phil/Sites/platinumlakemanagement/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('<!DOCTYPE html>...', Array, Array)
#27 /Users/phil/Sites/platinumlakemanagement/statamic/core/View/Antlers/Engine.php(75): Statamic\API\Parse::template('<!DOCTYPE html>...', Array)
#28 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/Users/phil/Sit...', Array)
#29 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#30 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#31 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#32 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/symfony/http-foundation/Response.php(200): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#33 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 200, Array)
#34 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(598): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 200, Array)
#35 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Controllers/StatamicController.php(163): response(Object(Illuminate\View\View))
#36 [internal function]: Statamic\Http\Controllers\StatamicController->index('/')
#37 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#38 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#39 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#40 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#44 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#45 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#46 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#47 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#48 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#53 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#56 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#58 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#68 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#69 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#71 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#72 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#74 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CP/DefaultLocale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#75 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#76 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#77 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#78 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#79 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#80 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#81 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#82 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#83 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#84 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#85 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#86 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#87 /Users/phil/Sites/platinumlakemanagement/index.php(128): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#88 {main}  
```

## Temporary Fix
[Slack](https://statamic.slack.com/archives/support-v2/p1463764413007717)

**Comment by jasonvarga** [comment]
Forgot to put this into 2.0.6.

Here's the actual fix that'll be in 2.0.8.

![screen shot 2016-06-01 at 9 18 11 am](https://cloud.githubusercontent.com/assets/105211/15710852/ccf59bf4-27d9-11e6-9064-fc9dc57e7943.png)

and for your copy/pasting pleasure:

```
use Statamic\API\Helper;

...

        $collections = Helper::ensureArray($collection);
        foreach ($collections as $collection) {
            if (! Content::collectionExists($collection)) {
                throw new \Exception("Collection [$collection] doesn't exist.");
            }
        }
        $this->collection = Content::entries($collections, null, true);
```
