### ISSUE TITLE
Error when trying to save entry as draft

### ISSUE THREAD

**Issue by bruzed** [statamic/v2-hub#754]
### Steps to reproduce
1. In cp, 'Create Entry' in a Collection
2. Turn off the 'Published' toggle, give it a title
3. 'Save' the entry.
### Expected behaviour

The new entry should be saved as draft.
### Actual behaviour
1. Error dialog: ![screen shot 2016-06-14 at 1 17 35 pm](https://cloud.githubusercontent.com/assets/136376/16052486/7c2919b8-3232-11e6-828c-f1dbb5b5028d.png)
2. '.md' file is created in the content directory but doesn't appear in the list on cp.
3. Clear the cache and refreshing the cp, the entry will appear in the list.
### Server configuration

**Operating system**:
OS X El Capitan 10.11.4

**Web server:**
Apache/2.2.29

**PHP version:**
5.6.10

**Statamic version:**
2.0.9

**Updated from an older Statamic or fresh install:**
Updated from 2.0.7.
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
[2016-06-14 17:17:31] dev.ERROR: exception 'League\Flysystem\FileNotFoundException' with message 'File not found at path: collections/legends/_test.md' in /Projects/LIN/dev/legends/statamic/vendor/league/flysystem/src/Filesystem.php:381
Stack trace:
#0 /Projects/LIN/dev/legends/statamic/vendor/league/flysystem/src/Filesystem.php(294): League\Flysystem\Filesystem->assertPresent('collections/leg...')
#1 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(215): League\Flysystem\Filesystem->getTimestamp('collections/leg...')
#2 /Projects/LIN/dev/legends/statamic/core/Filesystem/FileAccessor.php(147): Illuminate\Filesystem\FilesystemAdapter->lastModified('collections/leg...')
#3 /Projects/LIN/dev/legends/statamic/core/Stache/File/LocalizedContentCacheUpdater.php(161): Statamic\Filesystem\FileAccessor->lastModified('collections/leg...')
#4 /Projects/LIN/dev/legends/statamic/core/Stache/File/LocalizedContentCacheUpdater.php(99): Statamic\Stache\File\LocalizedContentCacheUpdater->updateCollections()
#5 /Projects/LIN/dev/legends/statamic/core/Stache/File/LocalizedContentCacheService.php(30): Statamic\Stache\File\LocalizedContentCacheUpdater->update(Object(Statamic\Stache\File\LocalizedContentCache))
#6 /Projects/LIN/dev/legends/statamic/core/Stache/File/ContentCacheUpdater.php(107): Statamic\Stache\File\LocalizedContentCacheService->update(Object(Statamic\Stache\File\LocalizedContentCache))
#7 /Projects/LIN/dev/legends/statamic/core/Stache/File/ContentCacheService.php(41): Statamic\Stache\File\ContentCacheUpdater->update(Object(Statamic\Stache\File\ContentCache))
#8 /Projects/LIN/dev/legends/statamic/core/Stache/CacheService.php(59): Statamic\Stache\File\ContentCacheService->update()
#9 /Projects/LIN/dev/legends/statamic/core/API/Stache.php(21): Statamic\Stache\CacheService->update()
#10 /Projects/LIN/dev/legends/statamic/core/CP/Publish/Publisher.php(216): Statamic\API\Stache::update()
#11 /Projects/LIN/dev/legends/statamic/core/CP/Publish/EntryPublisher.php(45): Statamic\CP\Publish\Publisher->save()
#12 /Projects/LIN/dev/legends/statamic/core/Http/Controllers/PublishController.php(603): Statamic\CP\Publish\EntryPublisher->publish()
#13 [internal function]: Statamic\Http\Controllers\PublishController->save()
#14 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#15 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('save', Array)
#16 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), 'save')
#17 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#18 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#20 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#22 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'save')
#23 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'save')
#24 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#25 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#27 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /Projects/LIN/dev/legends/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /Projects/LIN/dev/legends/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /Projects/LIN/dev/legends/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 /Projects/LIN/dev/legends/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#65 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#66 /Projects/LIN/dev/legends/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#67 /Projects/LIN/dev/legends/index.php(143): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#68 {main}  
```

**Comment by sarahkyler** [comment]
I get this exact same behavior in 2.0.7 as well, additionally those collections entries could not be set to unpublish. They would appear in the content folder with the prepended underscore but the system doesn't seem to recognize that they are unpublished.

**Comment by jasonvarga** [comment]
I can't replicate this - it seems to work perfectly here. Can you think of any more details? What kind of collection is that? Alphabetical, number, date?

**Comment by nmquebb** [comment]
I ran into this as well. The order was alphabetical. `filename.md` just gets tossed to the front of the list when `_filename.md`

**Comment by lukeagsmith** [comment]
I'm getting this too: it won't save a new entry when trying to save as draft.

The browser gives an error dialogue and the console gives a 500 error. The entry won't save until the entire is set to published.

Interesting side effect: 1 `.md` file is created in the collections folder, however there are now 4 entries showing for that file in the CP (1 for each time I hit save).

![screen shot 2016-07-15 at 18 23 59](https://cloud.githubusercontent.com/assets/16148258/16883055/035bc6de-4aba-11e6-9af1-c92ce6fbf900.png)

I think this might be related to https://github.com/statamic/v2-hub/issues/813 with collections not showing as being unpublished.

To confirm this only happens on alphabetic collections, dated collections and pages are fine.

**Comment by jasonvarga** [comment]
This issue is so old, and appears to be working here. I'm gonna close this. Please feel free to reopen if you run into this again.
