### ISSUE TITLE
Call to a member function toArray() on null in Content.php

### ISSUE THREAD

**Issue by thestepafter** [statamic/v2-hub#816]
### Steps to reproduce
Visit any page on my site and this error is logged. I don't see any content breaking.

### Expected behaviour
This error shouldn't occur.

### Actual behaviour
This error does occur.

### Server configuration
**Operating system**:
Homestead

**Web server:**
Homestead (Apache / nginx

**PHP version:**
Latest

**Statamic version:**
Latest

**Updated from an older Statamic or fresh install:**
Fresh install

**List of installed addons:**
None

#### Web server error log
None.

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-07-16 13:48:23] local.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function toArray() on null in /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/API/Content.php:173
Stack trace:
#0 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/bundles/Nav/NavTags.php(123): Statamic\API\Content::get('/site/themes/fo...')
#1 [internal function]: Statamic\Addons\Nav\NavTags->breadcrumbs('breadcrumbs')
#2 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/View/Antlers/Engine.php(161): call_user_func(Array, 'breadcrumbs')
#3 [internal function]: Statamic\View\Antlers\Engine::renderTag('nav', Array, '\n              ...', Array)
#4 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/View/Antlers/Parser.php(515): call_user_func_array(Array, Array)
#5 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/View/Antlers/Parser.php(125): Statamic\View\Antlers\Parser->parseCallbackTags('<!doctype html>...', Array, Array)
#6 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/View/Antlers/Template.php(38): Statamic\View\Antlers\Parser->parse('{{ partial:site...', Array, Array, false)
#7 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/API/Parse.php(22): Statamic\View\Antlers\Template::parse('{{ partial:site...', Array, Array)
#8 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/View/Antlers/Engine.php(75): Statamic\API\Parse::template('{{ partial:site...', Array)
#9 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(147): Statamic\View\Antlers\Engine->get('/home/vagrant/g...', Array)
#10 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(118): Illuminate\View\View->getContents()
#11 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/View/View.php(83): Illuminate\View\View->renderContents()
#12 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Http/Response.php(51): Illuminate\View\View->render()
#13 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Illuminate\View\View))
#14 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(57): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View), 404, Array)
#15 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(595): Illuminate\Routing\ResponseFactory->make(Object(Illuminate\View\View), 404, Array)
#16 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/Http/Controllers/StatamicController.php(381): response(Object(Illuminate\View\View), 404)
#17 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/Http/Controllers/StatamicController.php(132): Statamic\Http\Controllers\StatamicController->notFoundResponse()
#18 [internal function]: Statamic\Http\Controllers\StatamicController->index('site/themes/fou...')
#19 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#20 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('index', Array)
#21 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), 'index')
#22 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\StatamicController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'index')
#28 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'index')
#29 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#30 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#31 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#37 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#38 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#40 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#41 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/Http/Middleware/CP/DefaultLocale.php(23): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#62 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#63 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#65 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#67 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#68 /home/vagrant/gitlab/customers/nuuanufloral/public/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#69 /home/vagrant/gitlab/customers/nuuanufloral/public/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#70 {main}  
```

#### Browser log
None

**Comment by jackmcdade** [comment]
Not a bug, you must have some invalid data format or overriding native variables in your Pages. We can work thru it on the Lodge or if anyone is available in Slack.

**Comment by jasonvarga** [comment]
What URL are you visiting when you see this?

Does it happen on _every_ page?

Is it just an entry page?

Does the current page's parent actually a page? ie. If you're on `/blog/2015/01/post`, is `/blog/2015/01` a valid page?

Are you on a localized version of the site?

**Comment by thestepafter** [comment]
Hello Jason, you actually fixed this for me in Slack. Basically I removed from code for breadcrumbs, saved, and re-added it. We decided that it was most likely a cache issue.
