### ISSUE TITLE
Images not displaying in CP or theme

### ISSUE THREAD

**Issue by nolfranklin** [statamic/v2-hub#878]
### Steps to reproduce
1. Fresh install of Statamic, permissions correctly set.
2. Visiting /cp/assets/browse/main/img displays broken images (image attached)

![screenshot 2016-08-23 20 07 20](https://cloud.githubusercontent.com/assets/602683/17914092/42337fba-696d-11e6-9dfb-ec958b591073.png)

ex: image url (http://sitename.dev/img/id/3c266a5d-d4fb-4aa0-90e6-9fbff048f1f8?w=200&h=200&fit=crop&s=3a5ab9744f05d83df8a5e46f8e7b50c5)

Is "/img/id/" a folder that needs to be created or is this symlinked to the local/cache folder? 

### Server configuration
**Operating system**: OSX 10.10.5 (14F1909)

**Web server:** MAMP PRO

**PHP version:** 5.5.14

**Statamic version:** 2.1.2

**List of installed addons:**
- no addons, fresh install

#### Statamic error log (`/local/storage/logs/statamic.log`)
```
[2016-08-23 23:34:23] production.ERROR: exception 'ErrorException' with message 'file_put_contents(): Filename cannot be empty' in /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/league/glide/src/Server.php:487
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'file_put_conten...', '/Users/nolfrank...', 487, Array)
#1 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/league/glide/src/Server.php(487): file_put_contents('', '\xFF\xD8\xFF\xE1\x00\x18Exif\x00\x00II*...')
#2 /Users/nolfranklin/sites/fromthegroundup.io/statamic/core/Imaging/ImageGenerator.php(120): League\Glide\Server->makeImage('photo-147043415...', Array)
#3 /Users/nolfranklin/sites/fromthegroundup.io/statamic/core/Imaging/ImageGenerator.php(100): Statamic\Imaging\ImageGenerator->generate('photo-147043415...')
#4 /Users/nolfranklin/sites/fromthegroundup.io/statamic/core/Http/Controllers/GlideController.php(97): Statamic\Imaging\ImageGenerator->generateByAsset(Object(Statamic\Assets\Asset), Array)
#5 [internal function]: Statamic\Http\Controllers\GlideController->generateByAsset('9ce7e8a0-a1e0-4...')
#6 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#7 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('generateByAsset', Array)
#8 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\GlideController), Object(Illuminate\Routing\Route), 'generateByAsset')
#9 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#10 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#12 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#13 /Users/nolfranklin/sites/fromthegroundup.io/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
```

**Comment by nolfranklin** [comment]
Confirming this is happening on latest MAMP PRO as well. (3.5.2 + PHP 7.0.8)

**Comment by nolfranklin** [comment]
Confirming the images work when running "php please serve" just not in MAMP PRO.

**Comment by nolfranklin** [comment]
#563 suggestion fixed the issue. 

Fix: Switching Run Apache/MySQL server as user to "user" instead of "www" in Mamp.
