### ISSUE TITLE
DuplicateID Exception when unpublishing a collection parent & changing its slug at the same time

### ISSUE THREAD

**Issue by than** [statamic/v2-hub#895]
### Steps to reproduce
1. Edit a collection (I was using the default Redwood blog collection here)
2. Change the slug
3. Set the status to unpublished
4. Hit save
### Expected behavior

I would expect the slug of the page to change and the page to set its status to unpublished.
### Actual behavior

Exception thrown:

```
DuplicateIdException in AbstractDriver.php line 216:
Cannot add [pages/_4.blog/index.md] to Stache repository [pages]. File at [pages/4.blog/index.md] already exists in repository [pages] with an ID of [60962021-f154-4cd2-a1d7-035a12b6da9e].
```
### Server configuration

**Web server:**
Local

**PHP version:**
5.6.11

**Statamic version:**
2.1.3

**List of installed addons:**
None
#### Statamic error log (`/local/storage/logs/statamic.log`)

```
[2016-08-25 22:01:50] production.ERROR: exception 'Statamic\Exceptions\DuplicateIdException' with message 'Cannot add [pages/_4.blog/index.md] to Stache repository [pages]. File at [pages/4.blog/index.md] already exists in repository [pages] with an ID of [60962021-f154-4cd2-a1d7-035a12b6da9e].' in /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Drivers/AbstractDriver.php:216
Stack trace:
#0 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(348): Statamic\Stache\Drivers\AbstractDriver->ensureUniqueId(Object(Statamic\Data\Pages\Page))
#1 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(326): Statamic\Stache\Updater->ensureUniqueId(Object(Statamic\Data\Pages\Page))
#2 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(241): Statamic\Stache\Updater->ensureId(Object(Statamic\Data\Pages\Page))
#3 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Updater->Statamic\Stache\{closure}(Array, 'pages/_4.blog/i...')
#4 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(252): Illuminate\Support\Collection->each(Object(Closure))
#5 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(138): Statamic\Stache\Updater->updateItems(Object(Illuminate\Support\Collection))
#6 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Updater.php(106): Statamic\Stache\Updater->updateDefault()
#7 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/UpdateManager.php(56): Statamic\Stache\Updater->update()
#8 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\UpdateManager->Statamic\Stache\{closure}(Object(Statamic\Stache\Drivers\PagesDriver), 'pages')
#9 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/UpdateManager.php(64): Illuminate\Support\Collection->each(Object(Closure))
#10 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Stache/Manager.php(81): Statamic\Stache\UpdateManager->update()
#11 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Providers/StacheServiceProvider.php(125): Statamic\Stache\Manager->update()
#12 [internal function]: Statamic\Providers\StacheServiceProvider->boot(Object(Illuminate\Http\Request))
#13 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#14 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#15 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(546): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\StacheServiceProvider))
#16 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(648): Illuminate\Foundation\Application->register(Object(Statamic\Providers\StacheServiceProvider))
#17 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(628): Illuminate\Foundation\Application->registerDeferredProvider('Statamic\\Provid...', 'Statamic\\Stache...')
#18 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(671): Illuminate\Foundation\Application->loadDeferredProvider('Statamic\\Stache...')
#19 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\Foundation\Application->make('Statamic\\Stache...')
#20 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#21 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Container\Container->getDependencies(Array, Array)
#22 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Data\\S...', Array)
#23 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Data\\S...', Array)
#24 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(62): Illuminate\Foundation\Application->make('Statamic\\Data\\S...', Array)
#25 /Users/ttibbetts/Sites/csbgl.org/statamic/core/API/Collection.php(16): app('Statamic\\Data\\S...')
#26 /Users/ttibbetts/Sites/csbgl.org/statamic/core/API/Collection.php(26): Statamic\API\Collection::all()
#27 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Permissions/Permissions.php(57): Statamic\API\Collection::handles()
#28 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Permissions/Permissions.php(45): Statamic\Permissions\Permissions->buildCollectionsPermissions()
#29 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Providers/AuthServiceProvider.php(27): Statamic\Permissions\Permissions->build()
#30 [internal function]: Statamic\Providers\AuthServiceProvider->boot(Object(Illuminate\Auth\Access\Gate), Object(Statamic\Permissions\Permissions))
#31 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#32 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#33 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(546): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\AuthServiceProvider))
#34 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(648): Illuminate\Foundation\Application->register(Object(Statamic\Providers\AuthServiceProvider))
#35 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(628): Illuminate\Foundation\Application->registerDeferredProvider('Statamic\\Provid...', 'Illuminate\\Cont...')
#36 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(671): Illuminate\Foundation\Application->loadDeferredProvider('Illuminate\\Cont...')
#37 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(842): Illuminate\Foundation\Application->make('Illuminate\\Cont...')
#38 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\Container\Container->resolveClass(Object(ReflectionParameter))
#39 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(776): Illuminate\Container\Container->getDependencies(Array, Array)
#40 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(631): Illuminate\Container\Container->build('Statamic\\Http\\M...', Array)
#41 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Statamic\\Http\\M...', Array)
#42 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(123): Illuminate\Foundation\Application->make('Statamic\\Http\\M...')
#43 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#51 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#52 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#53 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#54 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#56 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#57 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#59 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#60 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#62 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#63 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#65 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#66 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#67 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#68 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#69 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#71 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#72 /Users/ttibbetts/Sites/csbgl.org/statamic/core/Http/Middleware/Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#73 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#74 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#75 /Users/ttibbetts/Sites/csbgl.org/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#76 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#77 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#78 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#79 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#80 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#81 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#82 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#83 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#84 /Users/ttibbetts/Sites/csbgl.org/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#85 /Users/ttibbetts/Sites/csbgl.org/index.php(128): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#86 {main}
```

**Comment by than** [comment]
I will also note that attempting to clear this with `php please clear:cache` throws the same exception.

**Comment by than** [comment]
Also confirmed this morning again that just toggling the publish status and saving works, as does changing the slug and saving. It's only when the two happen at the same time that the error occurs.

**Comment by AurelioDeRosa** [comment]
I have the same issue. I even tried to upgrade to PHP 7 but nothing changed.

**Comment by jasonvarga** [comment]
Upgrading PHP wont have any effect. Except maybe that you will be able to see the bug about 50% faster. :)

**Comment by AurelioDeRosa** [comment]
Try something is better than nothing I guess. It was worth checking if it was an incompatibility problem with the specific version.

**Comment by minthemiddle** [comment]
Same problem here. There is no explanation how to get rid of the problem. Not very useful help here either.

**Comment by manogi** [comment]
I have the same problem. Is there any solution yet?

**Comment by robbinfellow** [comment]
Encountered this issue as well on Statamic 2.6.4, solved by deleting the contents of `local/storage/framework/cache` manually.

**Comment by danielfowler** [comment]
Ya coulda waited til the 1-Year Anniversary, Jason. ;)
