### ISSUE TITLE
Bug: Call to a member function all() on null in ItemLoader.php:27

### ISSUE THREAD

**Issue by mikemartin** [statamic/v2-hub#941]
When editing a collection I've hit this error.

![screenshot 2016-09-08 17 21 56](https://cloud.githubusercontent.com/assets/414211/18372254/0a086148-75f0-11e6-8028-1521280c4360.png)

### Server configuration
**Operating system**: Mac

**Web server:** Valet

**PHP version:**

**Statamic version:** 2.1.7 and also on 2.1.8

**Updated from an older Statamic or fresh install:**

**List of installed addons:**

### Logs
If any logs (browser, server, or Statamic) are appropriate...
```
[2016-09-09 01:10:20] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function all() on null in /Users/mike/Sites/trychameleon/statamic/core/Stache/ItemLoader.php:27
Stack trace:
#0 [internal function]: Statamic\Stache\ItemLoader->Statamic\Stache\{closure}(NULL, 42)
#1 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(469): array_map(Object(Closure), Array, Array)
#2 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(482): Illuminate\Support\Collection->map(Object(Closure))
#3 /Users/mike/Sites/trychameleon/statamic/core/Stache/ItemLoader.php(28): Illuminate\Support\Collection->flatMap(Object(Closure))
#4 /Users/mike/Sites/trychameleon/statamic/core/Stache/Repository.php(236): Statamic\Stache\ItemLoader->load()
#5 /Users/mike/Sites/trychameleon/statamic/core/Stache/Repository.php(223): Statamic\Stache\Repository->load()
#6 /Users/mike/Sites/trychameleon/statamic/core/Stache/AggregateRepository.php(147): Statamic\Stache\Repository->getItems()
#7 [internal function]: Statamic\Stache\AggregateRepository->Statamic\Stache\{closure}(Object(Statamic\Stache\Repository), 'customers')
#8 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(469): array_map(Object(Closure), Array, Array)
#9 /Users/mike/Sites/trychameleon/statamic/core/Stache/AggregateRepository.php(148): Illuminate\Support\Collection->map(Object(Closure))
#10 /Users/mike/Sites/trychameleon/statamic/core/Stache/Drivers/EntriesDriver.php(127): Statamic\Stache\AggregateRepository->getItems()
#11 /Users/mike/Sites/trychameleon/statamic/core/Stache/Drivers/EntriesDriver.php(89): Statamic\Stache\Drivers\EntriesDriver->getPersistentItems(Object(Statamic\Stache\AggregateRepository))
#12 /Users/mike/Sites/trychameleon/statamic/core/Stache/Persister.php(56): Statamic\Stache\Drivers\EntriesDriver->toPersistentArray(Object(Statamic\Stache\AggregateRepository))
#13 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Support/Collection.php(135): Statamic\Stache\Persister->Statamic\Stache\{closure}('entries', 0)
#14 /Users/mike/Sites/trychameleon/statamic/core/Stache/Persister.php(60): Illuminate\Support\Collection->each(Object(Closure))
#15 /Users/mike/Sites/trychameleon/statamic/core/Stache/Manager.php(85): Statamic\Stache\Persister->persist(Object(Illuminate\Support\Collection))
#16 /Users/mike/Sites/trychameleon/statamic/core/Providers/StacheServiceProvider.php(130): Statamic\Stache\Manager->update()
#17 [internal function]: Statamic\Providers\StacheServiceProvider->boot(Object(Illuminate\Http\Request))
#18 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#19 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#20 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(Statamic\Providers\StacheServiceProvider))
#21 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(Statamic\Providers\StacheServiceProvider), 24)
#22 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#23 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#24 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Statamic\Application))
#25 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(222): Illuminate\Foundation\Application->bootstrapWith(Array)
#26 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(117): Illuminate\Foundation\Http\Kernel->bootstrap()
#27 /Users/mike/Sites/trychameleon/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#28 /Users/mike/Sites/trychameleon/index.php(127): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#29 /Users/mike/.composer/vendor/laravel/valet/server.php(106): require('/Users/mike/Sit...')
#30 {main}  
```

**Comment by jackmcdade** [comment]
Editing a collection, like an entry? or Configure > Collection?

**Comment by mikemartin** [comment]
Editing an Entry. I believe this was fixed by Jason's cache size improvements, I'm not seeing the issue anymore.

**Comment by jackmcdade** [comment]
Sweet! Feel free to reopen if it rears its head again.
