### ISSUE TITLE
2.1.10 Importer Taxonomies - Only Imports 1 Taxonomy Item

### ISSUE THREAD

**Issue by pmeissner** [statamic/v2-hub#956]
### Expected behaviour

Create taxonomy IDs when importing content.
### Actual behaviour

It only imports 1 taxonomy term. The loader spins indefinitely. No blog entries are created.
### Steps to reproduce
1.  Enter http://cayden.info into the importer.
2.  Import.
### Server configuration

**Operating system**:
v2 Site on MacOS 10.11.6   -   v1 Site on Linux Server

**Web server:**
Apache

**PHP version:**
v2 on PHP7.  v1 on PHP 5.5.36

**Statamic version:**
2.1.10 and 1.11.3 
### Logs

If any logs (browser, server, or Statamic) are appropriate...
Statamic Log

```
[2016-09-14 13:06:15] dev.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function taxonomyName() on null in /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Content/ContentCollection.php:162
Stack trace:
#0 /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Taxonomies/Term.php(168): Statamic\Data\Content\ContentCollection->filterByTaxonomy('25d16b41-5865-4...')
#1 /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Taxonomies/Term.php(314): Statamic\Data\Taxonomies\Term->collection()
#2 /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Taxonomies/Term.php(330): Statamic\Data\Taxonomies\Term->count()
#3 /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Data.php(572): Statamic\Data\Taxonomies\Term->supplement()
#4 /Users/phil/Sites/platinumlakemanagement/statamic/bundles/Search/SearchListener.php(57): Statamic\Data\Data->toArray()
#5 [internal function]: Statamic\Addons\Search\SearchListener->insert(Object(Statamic\Events\Stache\RepositoryItemInserted))
#6 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Array, Array)
#7 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('Statamic\\Events...', Array, false)
#8 /Users/phil/Sites/platinumlakemanagement/statamic/core/Stache/Repository.php(259): event(Object(Statamic\Events\Stache\RepositoryItemInserted))
#9 /Users/phil/Sites/platinumlakemanagement/statamic/core/Stache/Listeners/UpdateContent.php(54): Statamic\Stache\Repository->setItem('25d16b41-5865-4...', Object(Statamic\Data\Taxonomies\Term))
#10 [internal function]: Statamic\Stache\Listeners\UpdateContent->handle(Object(Statamic\Data\Taxonomies\Term))
#11 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(347): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Events\Dispatcher->Illuminate\Events\{closure}(Object(Statamic\Data\Taxonomies\Term))
#13 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Events/Dispatcher.php(221): call_user_func_array(Object(Closure), Array)
#14 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(355): Illuminate\Events\Dispatcher->fire('content.saved', Array, false)
#15 /Users/phil/Sites/platinumlakemanagement/statamic/core/Data/Content/Content.php(191): event('content.saved', Object(Statamic\Data\Taxonomies\Term))
#16 /Users/phil/Sites/platinumlakemanagement/statamic/core/Importing/Statamic/Migrator.php(118): Statamic\Data\Content\Content->save()
#17 /Users/phil/Sites/platinumlakemanagement/statamic/core/Importing/Statamic/Migrator.php(40): Statamic\Importing\Statamic\Migrator->createTaxonomyTerms()
#18 /Users/phil/Sites/platinumlakemanagement/statamic/core/Importing/Statamic/StatamicImporter.php(99): Statamic\Importing\Statamic\Migrator->migrate(Array, Array)
#19 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Controllers/ImportController.php(74): Statamic\Importing\Statamic\StatamicImporter->import(Array)
#20 [internal function]: Statamic\Http\Controllers\ImportController->import('statamic')
#21 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#22 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('import', Array)
#23 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\ImportController), Object(Illuminate\Routing\Route), 'import')
#24 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#25 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#28 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\ImportController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'import')
#30 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'import')
#31 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#32 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#33 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#34 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#35 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#46 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#47 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#48 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#49 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#51 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#52 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/PersistStache.php(22): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Statamic\Http\Middleware\PersistStache->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#61 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#63 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#64 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#66 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#67 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#69 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#70 /Users/phil/Sites/platinumlakemanagement/statamic/core/Http/Middleware/Glide.php(43): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 [internal function]: Statamic\Http\Middleware\Glide->handle(Object(Illuminate\Http\Request), Object(Closure))
#72 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#73 /Users/phil/Sites/platinumlakemanagement/statamic/core/StaticCaching/Middleware/Retrieve.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 [internal function]: Statamic\StaticCaching\Middleware\Retrieve->handle(Object(Illuminate\Http\Request), Object(Closure))
#75 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#76 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#77 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#78 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#79 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#80 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#81 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#82 /Users/phil/Sites/platinumlakemanagement/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#83 /Users/phil/Sites/platinumlakemanagement/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#84 {main}  
```

Here is the lone blog entry it is trying to import:

```

---
title: Lorim Ipsum Title
categories:
  - Cats
  - Dogs

---
Lorim Ipsum
```

**Comment by pmeissner** [comment]
I tried this on a fresh install of v2 and the importer worked no problem. ¯\_(ツ)_/¯

So if you want to close this out, not sure if this issue is worth tracking down.
