### ISSUE TITLE
Collection field break inside a Grid

### ISSUE THREAD

**Issue by joshmedeski** [statamic/v2-hub#988]
### Expected behaviour

Use a collection field inside a grid fieldtype
### Actual behaviour

The collection field inside a grid fieldtype returns "null" for all items of the collection.

_Side Note: There is also poor styling of the collection element inside the grid._
### Steps to reproduce
1. Add a collection filed inside a grid fieldtype
2. Assign the grid to a page
3. View the edit page in the control pane
4. Try to add an item from the collection side the grid's collection field
### Server configuration

**Operating system**: OS X El Capitan (v10.11.6)

**Web server:** nginx

**PHP version:** 7.0.3

**Statamic version:** 2.1.12

**Updated from an older Statamic or fresh install:** Update from older version

**List of installed addons:** findalab (custom plugin)
### Screenshot

<img width="1563" alt="screen shot 2016-09-26 at 1 34 31 pm" src="https://cloud.githubusercontent.com/assets/2036594/18847011/04802f88-83ee-11e6-9e3a-dd56170e4fbd.png">
### Logs

If any logs (browser, server, or Statamic) are appropriate...

```
Stack trace:
#0 /data/statamic/core/CP/Fieldset.php(219): Statamic\API\Fieldset::get('urine_tests')
#1 /data/statamic/core/CP/Fieldset.php(183): Statamic\CP\Fieldset->inlinePartials(Array)
#2 /data/statamic/core/CP/Fieldset.php(238): Statamic\CP\Fieldset->fields()
#3 /data/statamic/core/Data/Data.php(375): Statamic\CP\Fieldset->fieldtypes()
#4 /data/statamic/core/Http/Controllers/PublishController.php(547): Statamic\Data\Data->processedData()
#5 /data/statamic/core/Http/Controllers/PublishController.php(214): Statamic\Http\Controllers\PublishController->populateWithBlanks(Object(Statamic\Data\Entries\Entry))
#6 [internal function]: Statamic\Http\Controllers\PublishController->editEntry('tests', 'urine-drug-test...')
#7 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#8 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('editEntry', Array)
#9 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), 'editEntry')
#10 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#11 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#12 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#14 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#15 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(67): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Statamic\Http\Controllers\PublishController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'editEntry')
#16 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Statamic\\Http\\C...', 'editEntry')
#17 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#18 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#19 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#21 /data/statamic/core/Http/Middleware/CP/Authenticate.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 [internal function]: Statamic\Http\Middleware\CP\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#24 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#26 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#27 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(673): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#28 /data/statamic/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#29 /data/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#31 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 /data/statamic/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 [internal function]: Barryvdh\Debugbar\Middleware\Debugbar->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#35 /data/statamic/core/Http/Middleware/Outpost.php(52): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 [internal function]: Statamic\Http\Middleware\Outpost->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#38 /data/statamic/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#39 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#40 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#41 /data/statamic/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#43 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#44 /data/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#46 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#47 /data/statamic/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#48 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#49 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#50 /data/statamic/core/Http/Middleware/CP/DefaultLocale.php(28): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 [internal function]: Statamic\Http\Middleware\CP\DefaultLocale->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#53 /data/statamic/core/Http/Middleware/CheckForStaticallyCachedPage.php(35): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#54 [internal function]: Statamic\Http\Middleware\CheckForStaticallyCachedPage->handle(Object(Illuminate\Http\Request), Object(Closure))
#55 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#56 /data/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#59 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#60 /data/statamic/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#61 /data/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /data/statamic/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /data/index.php(155): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 {main}  
```

This needs to be resolved to continue with https://github.com/Medology/zenscreening/issues/37

**Comment by jasonvarga** [comment]
Show us your fieldset.

**Comment by joshmedeski** [comment]
You got it @jasonvarga 

```yaml
title: Urine Tests
create_title: Urine Drug Testing
fields:
  urine_drug_testing_panel_drugs:
    type: grid
    display: Urine Drug Testing Panel Drugs
    fields:
      drug:
        type: collection
        display: Drug
        instructions: null
        max_items: 1
        sort: null
        label: null
        collection: drugs
        mode: tags
      8_drug_test_panel:
        type: toggle
        display: 8-Drug Test Panel
        instructions: null
        validate:
      10_drug_test_panel:
        type: toggle
        display: 10-Drug Test Panel
        instructions: null
      12_drug_test_panel:
        type: toggle
        display: 12-Drug Test Panel
        instructions: null
      13_drug_test_panel:
        type: toggle
        display: 13-Drug Test Panel
        instructions: null
    mode: table
  drugs_test:
    type: collection
    display: Drugs Test
    collection: drugs
    mode: tags
```

**Comment by mikegraham00** [comment]
I'm seeing the same thing inside a replicator. V2.5.2

Any luck on fixing it?

**Comment by joshmedeski** [comment]
@mikegraham00 we ended up moving in a different direction with the field types. I'm not sure if this issue has been resolved by the Statamic team.

**Comment by jackmcdade** [comment]
Turns out the issue is the `null` value on your `label` field:

```
drug:
        type: collection
        display: Drug
        instructions: null
        max_items: 1
        sort: null 
        label: null #this right here
```

If you remove that (or set one such as `label: "{{ title }}"`, all is well. Of course, that was probably _created_ by the Fieldset builder, which means there's a bug. Which we fixed. For next release. :+1:

**Comment by joshmedeski** [comment]
Thanks @jackmcdade!
